<?php


/*

DON'T EDIT THIS FILE!

This file was automatically generated by the Lime parser generator.
The real source code you should be looking at is in one or more
grammar files in the Lime format.

THE ONLY REASON TO LOOK AT THIS FILE is to see where in the grammar
file that your error happened, because there are enough comments to
help you debug your grammar.

If you ignore this warning, you're shooting yourself in the brain,
not the foot.

*/

class spectql extends lime_parser {
var $qi = 0;
var $i = array (
  0 => 
  array (
    'flow' => 's 1',
    'expression' => 's 7',
    'resource' => 's 15',
    'calc' => 's 16',
    'resourceid' => 's 31',
    'name' => 's 87',
    'num' => 's 18',
    '\'(\'' => 's 28',
    'stmt' => 's 106',
    '\'start\'' => 'a \'start\'',
    '\'/\'' => 'r 14',
    '\'-\'' => 'r 14',
    '\'.\'' => 'r 16',
    '\'+\'' => 'r 16',
    '\'*\'' => 'r 16',
    '\':\'' => 'r 16',
    '#' => 'r 16',
  ),
  1 => 
  array (
    '\':\'' => 's 2',
    '#' => 'r 0',
  ),
  2 => 
  array (
    'format' => 's 3',
    'name' => 's 4',
    '\'-\'' => 'r 14',
    '#' => 'r 14',
  ),
  3 => 
  array (
    '#' => 'r 1',
  ),
  4 => 
  array (
    '\'-\'' => 's 5',
    '#' => 'r 50',
  ),
  5 => 
  array (
    'name' => 's 6',
    '\'-\'' => 'r 14',
    '\'(\'' => 'r 14',
    'LE' => 'r 14',
    'GE' => 'r 14',
    'NE' => 'r 14',
    '\'~\'' => 'r 14',
    '\'<\'' => 'r 14',
    'EQ' => 'r 14',
    '\'>\'' => 'r 14',
    'ALIAS' => 'r 14',
    'LN' => 'r 14',
    '\'/\'' => 'r 14',
    '\'?\'' => 'r 14',
    '\'{\'' => 'r 14',
    '\'.\'' => 'r 14',
    '\':\'' => 'r 14',
    '\'+\'' => 'r 14',
    '\',\'' => 'r 14',
    '\'}\'' => 'r 14',
    '\')\'' => 'r 14',
    '#' => 'r 14',
  ),
  6 => 
  array (
    '\'-\'' => 'r 13',
    '\'(\'' => 'r 13',
    'LE' => 'r 13',
    'GE' => 'r 13',
    'NE' => 'r 13',
    '\'~\'' => 'r 13',
    '\'<\'' => 'r 13',
    'EQ' => 'r 13',
    '\'>\'' => 'r 13',
    'ALIAS' => 'r 13',
    'LN' => 'r 13',
    '\'/\'' => 'r 13',
    '\'?\'' => 'r 13',
    '\'{\'' => 'r 13',
    '\'.\'' => 'r 13',
    '\':\'' => 'r 13',
    '\'+\'' => 'r 13',
    '\',\'' => 'r 13',
    '\'}\'' => 'r 13',
    '\')\'' => 'r 13',
    '#' => 'r 13',
  ),
  7 => 
  array (
    '\'.\'' => 's 8',
    '\':\'' => 'r 2',
    '#' => 'r 2',
  ),
  8 => 
  array (
    'name' => 's 9',
    '\'(\'' => 'r 14',
    '\'-\'' => 'r 14',
  ),
  9 => 
  array (
    '\'(\'' => 's 10',
    '\'-\'' => 's 5',
  ),
  10 => 
  array (
    'num' => 's 11',
    '\')\'' => 'r 16',
    '\'.\'' => 'r 16',
  ),
  11 => 
  array (
    '\')\'' => 's 12',
    '\'.\'' => 's 13',
  ),
  12 => 
  array (
    '\':\'' => 'r 3',
    '#' => 'r 3',
  ),
  13 => 
  array (
    'num' => 's 14',
    '\'.\'' => 'r 16',
    '\')\'' => 'r 16',
    '\',\'' => 'r 16',
    '\'?\'' => 'r 16',
    '\'/\'' => 'r 16',
    '\'{\'' => 'r 16',
    '\':\'' => 'r 16',
    '\'*\'' => 'r 16',
    '\'-\'' => 'r 16',
    '\'+\'' => 'r 16',
    '\'&\'' => 'r 16',
    '\'|\'' => 'r 16',
    '#' => 'r 16',
  ),
  14 => 
  array (
    '\'.\'' => 'r 15',
    '\')\'' => 'r 15',
    '\',\'' => 'r 15',
    '\'?\'' => 'r 15',
    '\'/\'' => 'r 15',
    '\'{\'' => 'r 15',
    '\':\'' => 'r 15',
    '\'*\'' => 'r 15',
    '\'-\'' => 'r 15',
    '\'+\'' => 'r 15',
    '\'&\'' => 'r 15',
    '\'|\'' => 'r 15',
    '#' => 'r 15',
  ),
  15 => 
  array (
    '\'.\'' => 'r 4',
    '\':\'' => 'r 4',
    '#' => 'r 4',
  ),
  16 => 
  array (
    '\'+\'' => 's 17',
    '\'-\'' => 's 22',
    '\'*\'' => 's 24',
    '\'/\'' => 's 26',
    '\'.\'' => 'r 5',
    '\':\'' => 'r 5',
    '#' => 'r 5',
  ),
  17 => 
  array (
    'num' => 's 18',
    'calc' => 's 21',
    '\'(\'' => 's 28',
    '\'.\'' => 'r 16',
    '\'+\'' => 'r 16',
    '\'-\'' => 'r 16',
    '\'*\'' => 'r 16',
    '\'/\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  18 => 
  array (
    '\'.\'' => 's 19',
    '\'+\'' => 'r 51',
    '\'-\'' => 'r 51',
    '\'*\'' => 'r 51',
    '\'/\'' => 'r 51',
    '\':\'' => 'r 51',
    '\')\'' => 'r 51',
    '#' => 'r 51',
  ),
  19 => 
  array (
    'num' => 's 20',
    '\'.\'' => 'r 16',
    '\'/\'' => 'r 16',
    '\'*\'' => 'r 16',
    '\'-\'' => 'r 16',
    '\'+\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  20 => 
  array (
    '\'.\'' => 'r 15',
    '\'+\'' => 'r 15',
    '\'-\'' => 'r 15',
    '\'*\'' => 'r 15',
    '\'/\'' => 'r 15',
    '\':\'' => 'r 15',
    '\')\'' => 'r 15',
    '#' => 'r 15',
  ),
  21 => 
  array (
    '\'+\'' => 'r 52',
    '\'-\'' => 'r 52',
    '\'*\'' => 's 24',
    '\'/\'' => 's 26',
    '\'.\'' => 'r 52',
    '\':\'' => 'r 52',
    '\')\'' => 'r 52',
    '#' => 'r 52',
  ),
  22 => 
  array (
    'num' => 's 18',
    'calc' => 's 23',
    '\'(\'' => 's 28',
    '\'.\'' => 'r 16',
    '\'+\'' => 'r 16',
    '\'-\'' => 'r 16',
    '\'*\'' => 'r 16',
    '\'/\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  23 => 
  array (
    '\'+\'' => 'r 53',
    '\'-\'' => 'r 53',
    '\'*\'' => 's 24',
    '\'/\'' => 's 26',
    '\'.\'' => 'r 53',
    '\':\'' => 'r 53',
    '\')\'' => 'r 53',
    '#' => 'r 53',
  ),
  24 => 
  array (
    'num' => 's 18',
    'calc' => 's 25',
    '\'(\'' => 's 28',
    '\'.\'' => 'r 16',
    '\'+\'' => 'r 16',
    '\'-\'' => 'r 16',
    '\'*\'' => 'r 16',
    '\'/\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  25 => 
  array (
    '\'+\'' => 'r 54',
    '\'-\'' => 'r 54',
    '\'*\'' => 'r 54',
    '\'/\'' => 'r 54',
    '\'.\'' => 'r 54',
    '\':\'' => 'r 54',
    '\')\'' => 'r 54',
    '#' => 'r 54',
  ),
  26 => 
  array (
    'num' => 's 18',
    'calc' => 's 27',
    '\'(\'' => 's 28',
    '\'.\'' => 'r 16',
    '\'+\'' => 'r 16',
    '\'-\'' => 'r 16',
    '\'*\'' => 'r 16',
    '\'/\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  27 => 
  array (
    '\'+\'' => 'r 55',
    '\'-\'' => 'r 55',
    '\'*\'' => 'r 55',
    '\'/\'' => 'r 55',
    '\'.\'' => 'r 55',
    '\':\'' => 'r 55',
    '\')\'' => 'r 55',
    '#' => 'r 55',
  ),
  28 => 
  array (
    'num' => 's 18',
    'calc' => 's 29',
    '\'(\'' => 's 28',
    '\'.\'' => 'r 16',
    '\'+\'' => 'r 16',
    '\'-\'' => 'r 16',
    '\'*\'' => 'r 16',
    '\'/\'' => 'r 16',
    '\')\'' => 'r 16',
  ),
  29 => 
  array (
    '\'+\'' => 's 17',
    '\'-\'' => 's 22',
    '\'*\'' => 's 24',
    '\'/\'' => 's 26',
    '\')\'' => 's 30',
  ),
  30 => 
  array (
    '\'/\'' => 'r 57',
    '\'*\'' => 'r 57',
    '\'-\'' => 'r 57',
    '\'+\'' => 'r 57',
    '\'.\'' => 'r 57',
    '\':\'' => 'r 57',
    '\')\'' => 'r 57',
    '#' => 'r 57',
  ),
  31 => 
  array (
    '\'{\'' => 's 32',
    '\'?\'' => 's 104',
    '\'/\'' => 's 91',
    '\'.\'' => 'r 8',
    '\':\'' => 'r 8',
    '#' => 'r 8',
  ),
  32 => 
  array (
    'selector' => 's 33',
    'name' => 's 74',
    'selectargument' => 's 103',
    'argument' => 's 101',
    'link' => 's 83',
    '\'*\'' => 's 84',
    'function' => 's 85',
    'ALIAS' => 'r 14',
    '\'-\'' => 'r 14',
    '\'(\'' => 'r 14',
    'LN' => 'r 14',
    '\'+\'' => 'r 14',
    '\',\'' => 'r 14',
    '\'}\'' => 'r 14',
  ),
  33 => 
  array (
    '\'}\'' => 's 34',
    '\',\'' => 's 73',
  ),
  34 => 
  array (
    '\'?\'' => 's 35',
    '\'.\'' => 'r 6',
    '\':\'' => 'r 6',
    '#' => 'r 6',
  ),
  35 => 
  array (
    'filterlist' => 's 36',
    'name' => 's 38',
    'filter' => 's 66',
    '\'(\'' => 's 70',
    '\'-\'' => 'r 14',
    'LE' => 'r 14',
    'GE' => 'r 14',
    'NE' => 'r 14',
    '\'~\'' => 'r 14',
    '\'<\'' => 'r 14',
    'EQ' => 'r 14',
    '\'>\'' => 'r 14',
  ),
  36 => 
  array (
    '\'&\'' => 's 37',
    '\'|\'' => 's 68',
    '\'.\'' => 'r 7',
    '\':\'' => 'r 7',
    '#' => 'r 7',
  ),
  37 => 
  array (
    'name' => 's 38',
    'filter' => 's 66',
    'filterlist' => 's 67',
    '\'(\'' => 's 70',
    '\'-\'' => 'r 14',
    'LE' => 'r 14',
    'GE' => 'r 14',
    'NE' => 'r 14',
    '\'~\'' => 'r 14',
    '\'<\'' => 'r 14',
    'EQ' => 'r 14',
    '\'>\'' => 'r 14',
  ),
  38 => 
  array (
    '\'-\'' => 's 5',
    '\'>\'' => 's 39',
    'EQ' => 's 42',
    '\'<\'' => 's 45',
    '\'~\'' => 's 48',
    'NE' => 's 50',
    'GE' => 's 53',
    'LE' => 's 56',
    '\'(\'' => 's 59',
  ),
  39 => 
  array (
    'num' => 's 40',
    'string' => 's 41',
    '\'.\'' => 'r 16',
    '\'&\'' => 'r 16',
    '\'|\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  40 => 
  array (
    '\'.\'' => 'r 24',
    '\'&\'' => 'r 24',
    '\'|\'' => 'r 24',
    '\':\'' => 'r 24',
    '\')\'' => 'r 24',
    '#' => 'r 24',
  ),
  41 => 
  array (
    '\'&\'' => 'r 21',
    '\'|\'' => 'r 21',
    '\'.\'' => 'r 21',
    '\':\'' => 'r 21',
    '\')\'' => 'r 21',
    '#' => 'r 21',
  ),
  42 => 
  array (
    'num' => 's 43',
    'string' => 's 44',
    '\'.\'' => 'r 16',
    '\'&\'' => 'r 16',
    '\'|\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  43 => 
  array (
    '\'.\'' => 'r 25',
    '\'&\'' => 'r 25',
    '\'|\'' => 'r 25',
    '\':\'' => 'r 25',
    '\')\'' => 'r 25',
    '#' => 'r 25',
  ),
  44 => 
  array (
    '\'&\'' => 'r 22',
    '\'|\'' => 'r 22',
    '\'.\'' => 'r 22',
    '\':\'' => 'r 22',
    '\')\'' => 'r 22',
    '#' => 'r 22',
  ),
  45 => 
  array (
    'num' => 's 46',
    'string' => 's 47',
    '\'.\'' => 'r 16',
    '\'&\'' => 'r 16',
    '\'|\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  46 => 
  array (
    '\'.\'' => 'r 26',
    '\'&\'' => 'r 26',
    '\'|\'' => 'r 26',
    '\':\'' => 'r 26',
    '\')\'' => 'r 26',
    '#' => 'r 26',
  ),
  47 => 
  array (
    '\'&\'' => 'r 23',
    '\'|\'' => 'r 23',
    '\'.\'' => 'r 23',
    '\':\'' => 'r 23',
    '\')\'' => 'r 23',
    '#' => 'r 23',
  ),
  48 => 
  array (
    'string' => 's 49',
  ),
  49 => 
  array (
    '\'&\'' => 'r 27',
    '\'|\'' => 'r 27',
    '\'.\'' => 'r 27',
    '\':\'' => 'r 27',
    '\')\'' => 'r 27',
    '#' => 'r 27',
  ),
  50 => 
  array (
    'num' => 's 51',
    'string' => 's 52',
    '\'.\'' => 'r 16',
    '\'&\'' => 'r 16',
    '\'|\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  51 => 
  array (
    '\'.\'' => 's 13',
    '\'&\'' => 'r 29',
    '\'|\'' => 'r 29',
    '\':\'' => 'r 29',
    '\')\'' => 'r 29',
    '#' => 'r 29',
  ),
  52 => 
  array (
    '\'&\'' => 'r 28',
    '\'|\'' => 'r 28',
    '\'.\'' => 'r 28',
    '\':\'' => 'r 28',
    '\')\'' => 'r 28',
    '#' => 'r 28',
  ),
  53 => 
  array (
    'num' => 's 54',
    'string' => 's 55',
    '\'.\'' => 'r 16',
    '\'&\'' => 'r 16',
    '\'|\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  54 => 
  array (
    '\'.\'' => 's 13',
    '\'&\'' => 'r 31',
    '\'|\'' => 'r 31',
    '\':\'' => 'r 31',
    '\')\'' => 'r 31',
    '#' => 'r 31',
  ),
  55 => 
  array (
    '\'&\'' => 'r 30',
    '\'|\'' => 'r 30',
    '\'.\'' => 'r 30',
    '\':\'' => 'r 30',
    '\')\'' => 'r 30',
    '#' => 'r 30',
  ),
  56 => 
  array (
    'num' => 's 57',
    'string' => 's 58',
    '\'.\'' => 'r 16',
    '\'&\'' => 'r 16',
    '\'|\'' => 'r 16',
    '\':\'' => 'r 16',
    '\')\'' => 'r 16',
    '#' => 'r 16',
  ),
  57 => 
  array (
    '\'.\'' => 's 13',
    '\'&\'' => 'r 33',
    '\'|\'' => 'r 33',
    '\':\'' => 'r 33',
    '\')\'' => 'r 33',
    '#' => 'r 33',
  ),
  58 => 
  array (
    '\'&\'' => 'r 32',
    '\'|\'' => 'r 32',
    '\'.\'' => 'r 32',
    '\':\'' => 'r 32',
    '\')\'' => 'r 32',
    '#' => 'r 32',
  ),
  59 => 
  array (
    'num' => 's 60',
    '\',\'' => 'r 16',
    '\'.\'' => 'r 16',
  ),
  60 => 
  array (
    '\'.\'' => 's 13',
    '\',\'' => 's 61',
  ),
  61 => 
  array (
    'num' => 's 62',
    '\',\'' => 'r 16',
    '\'.\'' => 'r 16',
  ),
  62 => 
  array (
    '\'.\'' => 's 13',
    '\',\'' => 's 63',
  ),
  63 => 
  array (
    'num' => 's 64',
    '\')\'' => 'r 16',
    '\'.\'' => 'r 16',
  ),
  64 => 
  array (
    '\'.\'' => 's 13',
    '\')\'' => 's 65',
  ),
  65 => 
  array (
    '\'&\'' => 'r 34',
    '\'|\'' => 'r 34',
    '\'.\'' => 'r 34',
    '\':\'' => 'r 34',
    '\')\'' => 'r 34',
    '#' => 'r 34',
  ),
  66 => 
  array (
    '\'&\'' => 'r 17',
    '\'|\'' => 'r 17',
    '\'.\'' => 'r 17',
    '\':\'' => 'r 17',
    '\')\'' => 'r 17',
    '#' => 'r 17',
  ),
  67 => 
  array (
    '\'&\'' => 'r 18',
    '\'|\'' => 's 68',
    '\'.\'' => 'r 18',
    '\':\'' => 'r 18',
    '\')\'' => 'r 18',
    '#' => 'r 18',
  ),
  68 => 
  array (
    'name' => 's 38',
    'filter' => 's 66',
    'filterlist' => 's 69',
    '\'(\'' => 's 70',
    '\'-\'' => 'r 14',
    'LE' => 'r 14',
    'GE' => 'r 14',
    'NE' => 'r 14',
    '\'~\'' => 'r 14',
    '\'<\'' => 'r 14',
    'EQ' => 'r 14',
    '\'>\'' => 'r 14',
  ),
  69 => 
  array (
    '\'&\'' => 'r 19',
    '\'|\'' => 'r 19',
    '\'.\'' => 'r 19',
    '\':\'' => 'r 19',
    '\')\'' => 'r 19',
    '#' => 'r 19',
  ),
  70 => 
  array (
    'name' => 's 38',
    'filter' => 's 66',
    'filterlist' => 's 71',
    '\'(\'' => 's 70',
    '\'-\'' => 'r 14',
    'LE' => 'r 14',
    'GE' => 'r 14',
    'NE' => 'r 14',
    '\'~\'' => 'r 14',
    '\'<\'' => 'r 14',
    'EQ' => 'r 14',
    '\'>\'' => 'r 14',
  ),
  71 => 
  array (
    '\'&\'' => 's 37',
    '\'|\'' => 's 68',
    '\')\'' => 's 72',
  ),
  72 => 
  array (
    '\'|\'' => 'r 20',
    '\'&\'' => 'r 20',
    '\'.\'' => 'r 20',
    '\':\'' => 'r 20',
    '\')\'' => 'r 20',
    '#' => 'r 20',
  ),
  73 => 
  array (
    'name' => 's 74',
    'selectargument' => 's 100',
    'argument' => 's 101',
    'link' => 's 83',
    '\'*\'' => 's 84',
    'function' => 's 85',
    'ALIAS' => 'r 14',
    '\'-\'' => 'r 14',
    '\'(\'' => 'r 14',
    'LN' => 'r 14',
    '\'+\'' => 'r 14',
    '\'}\'' => 'r 14',
    '\',\'' => 'r 14',
  ),
  74 => 
  array (
    '\'-\'' => 's 5',
    'ALIAS' => 's 75',
    '\'(\'' => 's 77',
    'LN' => 's 86',
    '\'+\'' => 'r 45',
    '\',\'' => 'r 45',
    '\'}\'' => 'r 45',
  ),
  75 => 
  array (
    'name' => 's 76',
    'argument' => 's 96',
    'link' => 's 83',
    '\'*\'' => 's 84',
    'function' => 's 85',
    '\'(\'' => 'r 14',
    '\'-\'' => 'r 14',
    'LN' => 'r 14',
    '\'+\'' => 'r 14',
    '\',\'' => 'r 14',
    '\'}\'' => 'r 14',
  ),
  76 => 
  array (
    '\'-\'' => 's 5',
    '\'(\'' => 's 77',
    'LN' => 's 86',
    '\'+\'' => 'r 45',
    '\',\'' => 'r 45',
    '\'}\'' => 'r 45',
    '\')\'' => 'r 45',
  ),
  77 => 
  array (
    'name' => 's 76',
    'argument' => 's 78',
    'link' => 's 83',
    '\'*\'' => 's 84',
    'function' => 's 85',
    '\'(\'' => 'r 14',
    '\'-\'' => 'r 14',
    'LN' => 'r 14',
    '\',\'' => 'r 14',
    '\')\'' => 'r 14',
  ),
  78 => 
  array (
    '\')\'' => 's 79',
    '\',\'' => 's 80',
  ),
  79 => 
  array (
    '\'+\'' => 'r 41',
    '\'-\'' => 'r 41',
    '\',\'' => 'r 41',
    '\'}\'' => 'r 41',
    '\')\'' => 'r 41',
  ),
  80 => 
  array (
    'name' => 's 76',
    'argument' => 's 81',
    'link' => 's 83',
    '\'*\'' => 's 84',
    'function' => 's 85',
    '\'(\'' => 'r 14',
    '\'-\'' => 'r 14',
    'LN' => 'r 14',
    '\')\'' => 'r 14',
  ),
  81 => 
  array (
    '\')\'' => 's 82',
  ),
  82 => 
  array (
    '\'+\'' => 'r 42',
    '\'-\'' => 'r 42',
    '\',\'' => 'r 42',
    '\'}\'' => 'r 42',
    '\')\'' => 'r 42',
  ),
  83 => 
  array (
    '\'+\'' => 'r 46',
    '\'-\'' => 'r 46',
    '\',\'' => 'r 46',
    '\'}\'' => 'r 46',
    '\')\'' => 'r 46',
  ),
  84 => 
  array (
    '\'+\'' => 'r 47',
    '\'-\'' => 'r 47',
    '\',\'' => 'r 47',
    '\'}\'' => 'r 47',
    '\')\'' => 'r 47',
  ),
  85 => 
  array (
    '\'+\'' => 'r 48',
    '\'-\'' => 'r 48',
    '\',\'' => 'r 48',
    '\'}\'' => 'r 48',
    '\')\'' => 'r 48',
  ),
  86 => 
  array (
    'name' => 's 87',
    'resourceid' => 's 90',
    '\'/\'' => 'r 14',
    '\'-\'' => 'r 14',
  ),
  87 => 
  array (
    '\'/\'' => 's 88',
    '\'-\'' => 's 5',
  ),
  88 => 
  array (
    'name' => 's 89',
    '\'-\'' => 'r 14',
    '\'/\'' => 'r 14',
    '\'?\'' => 'r 14',
    '\'{\'' => 'r 14',
    '\'.\'' => 'r 14',
    '\':\'' => 'r 14',
    '#' => 'r 14',
  ),
  89 => 
  array (
    '\'-\'' => 's 5',
    '\'/\'' => 'r 10',
    '\'?\'' => 'r 10',
    '\'{\'' => 'r 10',
    '\'.\'' => 'r 10',
    '\':\'' => 'r 10',
    '#' => 'r 10',
  ),
  90 => 
  array (
    '\'/\'' => 's 91',
    '\'.\'' => 's 94',
  ),
  91 => 
  array (
    'name' => 's 92',
    'num' => 's 93',
    '\'-\'' => 'r 14',
    '\'/\'' => 'r 14',
    '\'?\'' => 'r 14',
    '\'{\'' => 'r 14',
    '\'.\'' => 'r 14',
    '\':\'' => 'r 14',
    '#' => 'r 14',
  ),
  92 => 
  array (
    '\'-\'' => 's 5',
    '\'/\'' => 'r 11',
    '\'?\'' => 'r 11',
    '\'{\'' => 'r 11',
    '\'.\'' => 'r 11',
    '\':\'' => 'r 11',
    '#' => 'r 11',
  ),
  93 => 
  array (
    '\'.\'' => 'r 12',
    '\'?\'' => 'r 12',
    '\'/\'' => 'r 12',
    '\'{\'' => 'r 12',
    '\':\'' => 'r 12',
    '#' => 'r 12',
  ),
  94 => 
  array (
    'name' => 's 95',
    '\'-\'' => 'r 14',
    '\'+\'' => 'r 14',
    '\',\'' => 'r 14',
    '\'}\'' => 'r 14',
    '\')\'' => 'r 14',
  ),
  95 => 
  array (
    '\'-\'' => 's 5',
    '\'+\'' => 'r 49',
    '\',\'' => 'r 49',
    '\'}\'' => 'r 49',
    '\')\'' => 'r 49',
  ),
  96 => 
  array (
    'order' => 's 97',
    '\'+\'' => 's 98',
    '\'-\'' => 's 99',
    '\',\'' => 'r 39',
    '\'}\'' => 'r 39',
  ),
  97 => 
  array (
    '\',\'' => 'r 40',
    '\'}\'' => 'r 40',
  ),
  98 => 
  array (
    '\',\'' => 'r 43',
    '\'}\'' => 'r 43',
  ),
  99 => 
  array (
    '\',\'' => 'r 44',
    '\'}\'' => 'r 44',
  ),
  100 => 
  array (
    '\'}\'' => 'r 36',
    '\',\'' => 'r 36',
  ),
  101 => 
  array (
    'order' => 's 102',
    '\'+\'' => 's 98',
    '\'-\'' => 's 99',
    '\',\'' => 'r 37',
    '\'}\'' => 'r 37',
  ),
  102 => 
  array (
    '\',\'' => 'r 38',
    '\'}\'' => 'r 38',
  ),
  103 => 
  array (
    '\',\'' => 'r 35',
    '\'}\'' => 'r 35',
  ),
  104 => 
  array (
    'filterlist' => 's 105',
    'name' => 's 38',
    'filter' => 's 66',
    '\'(\'' => 's 70',
    '\'-\'' => 'r 14',
    'LE' => 'r 14',
    'GE' => 'r 14',
    'NE' => 'r 14',
    '\'~\'' => 'r 14',
    '\'<\'' => 'r 14',
    'EQ' => 'r 14',
    '\'>\'' => 'r 14',
  ),
  105 => 
  array (
    '\'&\'' => 's 37',
    '\'|\'' => 's 68',
    '\'.\'' => 'r 9',
    '\':\'' => 'r 9',
    '#' => 'r 9',
  ),
  106 => 
  array (
    '#' => 'r 58',
  ),
);
function reduce_0_stmt_1($tokens, &$result) {
#
# (0) stmt :=  flow
#
$result = reset($tokens);

}

function reduce_1_stmt_2($tokens, &$result) {
#
# (1) stmt :=  flow  ':'  format
#
$result = reset($tokens);

}

function reduce_2_flow_1($tokens, &$result) {
#
# (2) flow :=  expression
#
$result = reset($tokens);

}

function reduce_3_flow_2($tokens, &$result) {
#
# (3) flow :=  expression  '.'  name  '('  num  ')'
#
$result = reset($tokens);
$e =& $tokens[0];
$function =& $tokens[2];
$n1 =& $tokens[4];
 if($function == "limit"){ /* TODO */ $result = null;}else{ $result = createAggregatorFilter($function,$n1);/* TODO create function php file to map constants*/  } 
}

function reduce_4_expression_1($tokens, &$result) {
#
# (4) expression :=  resource
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_5_expression_2($tokens, &$result) {
#
# (5) expression :=  calc
#
$result = reset($tokens);
 /* TODO execute calculation */ $result = $tokens[0]->execute(); 
}

function reduce_6_resource_1($tokens, &$result) {
#
# (6) resource :=  resourceid  '{'  selector  '}'
#
$result = reset($tokens);
$sel =& $tokens[2];
 $columns = new ColumnSelectionFilter($sel["filters"]); 
                                             $columns->setSource(new Identifier($tokens[0])); /* $sorts = new SORTOBJECT(); 
                                             $sort->setSource($columns); $result = $sorts;*/ $result = $columns; 
}

function reduce_7_resource_2($tokens, &$result) {
#
# (7) resource :=  resourceid  '{'  selector  '}'  '?'  filterlist
#
$result = reset($tokens);
$sel =& $tokens[2];
$fl =& $tokens[5];
 $expressionFilter = new FilterByExpressionFilter($fl); 
                                                     $columns = new ColumnSelectionFilter($sel["filters"]); 
                                                     $columns->setSource($expressionFilter); $expressionFilter->setSource(new Identifier($tokens[0])); 
                                                     /* $sorts = new SORTOBJECT(); $sort->setSource($columns); $result = $sorts;*/ $result = $columns; 
}

function reduce_8_resource_3($tokens, &$result) {
#
# (8) resource :=  resourceid
#
$result = reset($tokens);
 $result = new Identifier($tokens[0]); 
}

function reduce_9_resource_4($tokens, &$result) {
#
# (9) resource :=  resourceid  '?'  filterlist
#
$result = reset($tokens);
 $result = new FilterByExpressionFilter($tokens[2]); $result->setSource(new Identifier($tokens[0])); 
}

function reduce_10_resourceid_1($tokens, &$result) {
#
# (10) resourceid :=  name  '/'  name
#
$result = reset($tokens);
 $result = $tokens[0] . "." . $tokens[2]; 
}

function reduce_11_resourceid_2($tokens, &$result) {
#
# (11) resourceid :=  resourceid  '/'  name
#
$result = reset($tokens);
 $result = $tokens[0] . "." . $tokens[2]; 
}

function reduce_12_resourceid_3($tokens, &$result) {
#
# (12) resourceid :=  resourceid  '/'  num
#
$result = reset($tokens);
 $result = $tokens[0] . "." . $tokens[2]; 
}

function reduce_13_name_1($tokens, &$result) {
#
# (13) name :=  name  '-'  name
#
$result = reset($tokens);
 $result = $tokens[0] . "-" . $tokens[2]; 
}

function reduce_14_name_2($tokens, &$result) {
#
# (14) name :=
#
$result = reset($tokens);

}

function reduce_15_num_1($tokens, &$result) {
#
# (15) num :=  num  '.'  num
#
$result = reset($tokens);
 $result = new Constant((double) ($tokens[0] . "." . $tokens[2]));  
}

function reduce_16_num_2($tokens, &$result) {
#
# (16) num :=
#
$result = reset($tokens);

}

function reduce_17_filterlist_1($tokens, &$result) {
#
# (17) filterlist :=  filter
#
$result = reset($tokens);
 $result = $tokens[0]; 
}

function reduce_18_filterlist_2($tokens, &$result) {
#
# (18) filterlist :=  filterlist  '&'  filterlist
#
$result = reset($tokens);
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_AND,$tokens[0],$tokens[2]); 
}

function reduce_19_filterlist_3($tokens, &$result) {
#
# (19) filterlist :=  filterlist  '|'  filterlist
#
$result = reset($tokens);
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_OR,$tokens[0],$tokens[2]); 
}

function reduce_20_filterlist_4($tokens, &$result) {
#
# (20) filterlist :=  '('  filterlist  ')'
#
$result = reset($tokens);
$list =& $tokens[1];
 $result = $list;
}

function reduce_21_filter_1($tokens, &$result) {
#
# (21) filter :=  name  '>'  string
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result =  new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_THAN, new Identifier($a),new Constant($b)); 
}

function reduce_22_filter_2($tokens, &$result) {
#
# (22) filter :=  name  EQ  string
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_EQUAL,new Identifier($a),new Constant($b)); 
}

function reduce_23_filter_3($tokens, &$result) {
#
# (23) filter :=  name  '<'  string
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_THAN, new Identifier($a),new Constant($b)); 
}

function reduce_24_filter_4($tokens, &$result) {
#
# (24) filter :=  name  '>'  num
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_LARGER_THAN, new Identifier($a),new Constant($b)); 
}

function reduce_25_filter_5($tokens, &$result) {
#
# (25) filter :=  name  EQ  num
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_EQUAL,new Identifier($a),new Constant($b)); 
}

function reduce_26_filter_6($tokens, &$result) {
#
# (26) filter :=  name  '<'  num
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_THAN, new Identifier($a),new Constant($b)); 
}

function reduce_27_filter_7($tokens, &$result) {
#
# (27) filter :=  name  '~'  string
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_MATCH_REGEX, new Identifier($a),new Constant("/.*".preg_quote($b).".*/")); 
}

function reduce_28_filter_8($tokens, &$result) {
#
# (28) filter :=  name  NE  string
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_NOTEQUAL,new Identifier($a),new Constant($b)); 
}

function reduce_29_filter_9($tokens, &$result) {
#
# (29) filter :=  name  NE  num
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_NOTEQUAL,new Identifier($a),new Constant($b)); 
}

function reduce_30_filter_10($tokens, &$result) {
#
# (30) filter :=  name  GE  string
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_LARGER_OR_EQUAL_THAN,new Identifier($a),new Constant($b)); 
}

function reduce_31_filter_11($tokens, &$result) {
#
# (31) filter :=  name  GE  num
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_LARGER_OR_EQUAL_THAN,new Identifier($a),new Constant($b)); 
}

function reduce_32_filter_12($tokens, &$result) {
#
# (32) filter :=  name  LE  string
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_OR_EQUAL_THAN,new Identifier($a),new Constant($b)); 
}

function reduce_33_filter_13($tokens, &$result) {
#
# (33) filter :=  name  LE  num
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_OR_EQUAL_THAN,new Identifier($a),new Constant($b)); 
}

function reduce_34_filter_14($tokens, &$result) {
#
# (34) filter :=  name  '('  num  ','  num  ','  num  ')'
#
$result = reset($tokens);
$function =& $tokens[0];
$lat =& $tokens[2];
$long =& $tokens[4];
$radius =& $tokens[6];
 /* TODO in radius function (ternary function)*/ 
}

function reduce_35_selector_1($tokens, &$result) {
#
# (35) selector :=  selectargument
#
$result = reset($tokens);
$arg =& $tokens[0];
 $result = $tokens[0]; 
}

function reduce_36_selector_2($tokens, &$result) {
#
# (36) selector :=  selector  ','  selectargument
#
$result = reset($tokens);
$arg =& $tokens[2];
 $filters = array_merge($tokens[0]["filters"],$tokens[2]["filters"]); 
                                    $sorts = array_merge($tokens[0]["sorts"],$tokens[2]["sorts"]);
                                    $result = array("filters"=>$filters,"sorts"=>$sorts); 
}

function reduce_37_selectargument_1($tokens, &$result) {
#
# (37) selectargument :=  argument
#
$result = reset($tokens);
$arg =& $tokens[0];
 $result = array("filters" => array(new ColumnSelectionFilterColumn($arg,null)), "sorts" => array()); 
}

function reduce_38_selectargument_2($tokens, &$result) {
#
# (38) selectargument :=  argument  order
#
$result = reset($tokens);
$arg =& $tokens[0];
 $result = array( "filters" => array(new ColumnSelectionFilterColumn($arg,null)), "sorts" => array()); /* eens sort by functions bestaan, $result = array() van twee arrays van argument, en een array van alle argumenten waarop moet gesorteerd worden */ 
}

function reduce_39_selectargument_3($tokens, &$result) {
#
# (39) selectargument :=  name  ALIAS  argument
#
$result = reset($tokens);
$arg =& $tokens[2];
$result = array("filters" => array(new ColumnSelectionFilterColumn($arg,$tokens[0])), "sorts" => array());
}

function reduce_40_selectargument_4($tokens, &$result) {
#
# (40) selectargument :=  name  ALIAS  argument  order
#
$result = reset($tokens);
$arg =& $tokens[2];
$result = array("filters" => array(new ColumnSelectionFilterColumn($arg,$tokens[0])), "sorts" => array());
}

function reduce_41_function_1($tokens, &$result) {
#
# (41) function :=  name  '('  argument  ')'
#
$result = reset($tokens);
 $result = createUnaryFunction($tokens[0],$tokens[2]); 
}

function reduce_42_function_2($tokens, &$result) {
#
# (42) function :=  name  '('  argument  ','  argument  ')'
#
$result = reset($tokens);
 $result = createBinaryFunction($tokens[0],$tokens[2],$tokens[4]); 
}

function reduce_43_order_1($tokens, &$result) {
#
# (43) order :=  '+'
#
$result = reset($tokens);
 /* SORT BY ascending */ $result = 1; 
}

function reduce_44_order_2($tokens, &$result) {
#
# (44) order :=  '-'
#
$result = reset($tokens);
 /* SORT BY descending  */ $result = -1; 
}

function reduce_45_argument_1($tokens, &$result) {
#
# (45) argument :=  name
#
$result = reset($tokens);
$name =& $tokens[0];
 $result = new Identifier($name); 
}

function reduce_46_argument_2($tokens, &$result) {
#
# (46) argument :=  link
#
$result = reset($tokens);

}

function reduce_47_argument_3($tokens, &$result) {
#
# (47) argument :=  '*'
#
$result = reset($tokens);
 $result = new Identifier('*'); 
}

function reduce_48_argument_4($tokens, &$result) {
#
# (48) argument :=  function
#
$result = reset($tokens);
 $result = $tokens[0];
}

function reduce_49_link_1($tokens, &$result) {
#
# (49) link :=  name  LN  resourceid  '.'  name
#
$result = reset($tokens);
 /* joined resource */ 
}

function reduce_50_format_1($tokens, &$result) {
#
# (50) format :=  name
#
$result = reset($tokens);
 /* do nothing, format isnt used in the AST for it is an abstract filter tree , format is not a filter.*/ 
}

function reduce_51_calc_1($tokens, &$result) {
#
# (51) calc :=  num
#
$result = reset($tokens);
 $result = new Constant($tokens[0]); 
}

function reduce_52_calc_2($tokens, &$result) {
#
# (52) calc :=  calc  '+'  calc
#
$result = reset($tokens);
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_PLUS, $tokens[0], $tokens[2]);  
}

function reduce_53_calc_3($tokens, &$result) {
#
# (53) calc :=  calc  '-'  calc
#
$result = reset($tokens);
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_MINUS, $tokens[0], $tokens[2]); 
}

function reduce_54_calc_4($tokens, &$result) {
#
# (54) calc :=  calc  '*'  calc
#
$result = reset($tokens);
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_MULTIPLY, $tokens[0], $tokens[2]); 
}

function reduce_55_calc_5($tokens, &$result) {
#
# (55) calc :=  calc  '/'  calc
#
$result = reset($tokens);
 $result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_DIVIDE, $tokens[0], $tokens[2]); 
}

function reduce_56_calc_6($tokens, &$result) {
#
# (56) calc :=  num  '.'  num
#
$result = reset($tokens);
 $result = new Constant((double)($tokens[0] . "." . $tokens[2])); 
}

function reduce_57_calc_7($tokens, &$result) {
#
# (57) calc :=  '('  calc  ')'
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_58_start_1($tokens, &$result) {
#
# (58) 'start' :=  stmt
#
$result = reset($tokens);

}

var $method = array (
  0 => 'reduce_0_stmt_1',
  1 => 'reduce_1_stmt_2',
  2 => 'reduce_2_flow_1',
  3 => 'reduce_3_flow_2',
  4 => 'reduce_4_expression_1',
  5 => 'reduce_5_expression_2',
  6 => 'reduce_6_resource_1',
  7 => 'reduce_7_resource_2',
  8 => 'reduce_8_resource_3',
  9 => 'reduce_9_resource_4',
  10 => 'reduce_10_resourceid_1',
  11 => 'reduce_11_resourceid_2',
  12 => 'reduce_12_resourceid_3',
  13 => 'reduce_13_name_1',
  14 => 'reduce_14_name_2',
  15 => 'reduce_15_num_1',
  16 => 'reduce_16_num_2',
  17 => 'reduce_17_filterlist_1',
  18 => 'reduce_18_filterlist_2',
  19 => 'reduce_19_filterlist_3',
  20 => 'reduce_20_filterlist_4',
  21 => 'reduce_21_filter_1',
  22 => 'reduce_22_filter_2',
  23 => 'reduce_23_filter_3',
  24 => 'reduce_24_filter_4',
  25 => 'reduce_25_filter_5',
  26 => 'reduce_26_filter_6',
  27 => 'reduce_27_filter_7',
  28 => 'reduce_28_filter_8',
  29 => 'reduce_29_filter_9',
  30 => 'reduce_30_filter_10',
  31 => 'reduce_31_filter_11',
  32 => 'reduce_32_filter_12',
  33 => 'reduce_33_filter_13',
  34 => 'reduce_34_filter_14',
  35 => 'reduce_35_selector_1',
  36 => 'reduce_36_selector_2',
  37 => 'reduce_37_selectargument_1',
  38 => 'reduce_38_selectargument_2',
  39 => 'reduce_39_selectargument_3',
  40 => 'reduce_40_selectargument_4',
  41 => 'reduce_41_function_1',
  42 => 'reduce_42_function_2',
  43 => 'reduce_43_order_1',
  44 => 'reduce_44_order_2',
  45 => 'reduce_45_argument_1',
  46 => 'reduce_46_argument_2',
  47 => 'reduce_47_argument_3',
  48 => 'reduce_48_argument_4',
  49 => 'reduce_49_link_1',
  50 => 'reduce_50_format_1',
  51 => 'reduce_51_calc_1',
  52 => 'reduce_52_calc_2',
  53 => 'reduce_53_calc_3',
  54 => 'reduce_54_calc_4',
  55 => 'reduce_55_calc_5',
  56 => 'reduce_56_calc_6',
  57 => 'reduce_57_calc_7',
  58 => 'reduce_58_start_1',
);
var $a = array (
  0 => 
  array (
    'symbol' => 'stmt',
    'len' => 1,
    'replace' => true,
  ),
  1 => 
  array (
    'symbol' => 'stmt',
    'len' => 3,
    'replace' => true,
  ),
  2 => 
  array (
    'symbol' => 'flow',
    'len' => 1,
    'replace' => true,
  ),
  3 => 
  array (
    'symbol' => 'flow',
    'len' => 6,
    'replace' => true,
  ),
  4 => 
  array (
    'symbol' => 'expression',
    'len' => 1,
    'replace' => true,
  ),
  5 => 
  array (
    'symbol' => 'expression',
    'len' => 1,
    'replace' => true,
  ),
  6 => 
  array (
    'symbol' => 'resource',
    'len' => 4,
    'replace' => true,
  ),
  7 => 
  array (
    'symbol' => 'resource',
    'len' => 6,
    'replace' => true,
  ),
  8 => 
  array (
    'symbol' => 'resource',
    'len' => 1,
    'replace' => true,
  ),
  9 => 
  array (
    'symbol' => 'resource',
    'len' => 3,
    'replace' => true,
  ),
  10 => 
  array (
    'symbol' => 'resourceid',
    'len' => 3,
    'replace' => true,
  ),
  11 => 
  array (
    'symbol' => 'resourceid',
    'len' => 3,
    'replace' => true,
  ),
  12 => 
  array (
    'symbol' => 'resourceid',
    'len' => 3,
    'replace' => true,
  ),
  13 => 
  array (
    'symbol' => 'name',
    'len' => 3,
    'replace' => true,
  ),
  14 => 
  array (
    'symbol' => 'name',
    'len' => 0,
    'replace' => true,
  ),
  15 => 
  array (
    'symbol' => 'num',
    'len' => 3,
    'replace' => true,
  ),
  16 => 
  array (
    'symbol' => 'num',
    'len' => 0,
    'replace' => true,
  ),
  17 => 
  array (
    'symbol' => 'filterlist',
    'len' => 1,
    'replace' => true,
  ),
  18 => 
  array (
    'symbol' => 'filterlist',
    'len' => 3,
    'replace' => true,
  ),
  19 => 
  array (
    'symbol' => 'filterlist',
    'len' => 3,
    'replace' => true,
  ),
  20 => 
  array (
    'symbol' => 'filterlist',
    'len' => 3,
    'replace' => true,
  ),
  21 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  22 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  23 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  24 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  25 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  26 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  27 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  28 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  29 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  30 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  31 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  32 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  33 => 
  array (
    'symbol' => 'filter',
    'len' => 3,
    'replace' => true,
  ),
  34 => 
  array (
    'symbol' => 'filter',
    'len' => 8,
    'replace' => true,
  ),
  35 => 
  array (
    'symbol' => 'selector',
    'len' => 1,
    'replace' => true,
  ),
  36 => 
  array (
    'symbol' => 'selector',
    'len' => 3,
    'replace' => true,
  ),
  37 => 
  array (
    'symbol' => 'selectargument',
    'len' => 1,
    'replace' => true,
  ),
  38 => 
  array (
    'symbol' => 'selectargument',
    'len' => 2,
    'replace' => true,
  ),
  39 => 
  array (
    'symbol' => 'selectargument',
    'len' => 3,
    'replace' => true,
  ),
  40 => 
  array (
    'symbol' => 'selectargument',
    'len' => 4,
    'replace' => true,
  ),
  41 => 
  array (
    'symbol' => 'function',
    'len' => 4,
    'replace' => true,
  ),
  42 => 
  array (
    'symbol' => 'function',
    'len' => 6,
    'replace' => true,
  ),
  43 => 
  array (
    'symbol' => 'order',
    'len' => 1,
    'replace' => true,
  ),
  44 => 
  array (
    'symbol' => 'order',
    'len' => 1,
    'replace' => true,
  ),
  45 => 
  array (
    'symbol' => 'argument',
    'len' => 1,
    'replace' => true,
  ),
  46 => 
  array (
    'symbol' => 'argument',
    'len' => 1,
    'replace' => true,
  ),
  47 => 
  array (
    'symbol' => 'argument',
    'len' => 1,
    'replace' => true,
  ),
  48 => 
  array (
    'symbol' => 'argument',
    'len' => 1,
    'replace' => true,
  ),
  49 => 
  array (
    'symbol' => 'link',
    'len' => 5,
    'replace' => true,
  ),
  50 => 
  array (
    'symbol' => 'format',
    'len' => 1,
    'replace' => true,
  ),
  51 => 
  array (
    'symbol' => 'calc',
    'len' => 1,
    'replace' => true,
  ),
  52 => 
  array (
    'symbol' => 'calc',
    'len' => 3,
    'replace' => true,
  ),
  53 => 
  array (
    'symbol' => 'calc',
    'len' => 3,
    'replace' => true,
  ),
  54 => 
  array (
    'symbol' => 'calc',
    'len' => 3,
    'replace' => true,
  ),
  55 => 
  array (
    'symbol' => 'calc',
    'len' => 3,
    'replace' => true,
  ),
  56 => 
  array (
    'symbol' => 'calc',
    'len' => 3,
    'replace' => true,
  ),
  57 => 
  array (
    'symbol' => 'calc',
    'len' => 3,
    'replace' => true,
  ),
  58 => 
  array (
    'symbol' => '\'start\'',
    'len' => 1,
    'replace' => true,
  ),
);
}
