<?php


/*

DON'T EDIT THIS FILE!

This file was automatically generated by the Lime parser generator.
The real source code you should be looking at is in one or more
grammar files in the Lime format.

THE ONLY REASON TO LOOK AT THIS FILE is to see where in the grammar
file that your error happened, because there are enough comments to
help you debug your grammar.

If you ignore this warning, you're shooting yourself in the brain,
not the foot.

*/

class SQLgrammar extends lime_parser {
var $qi = 0;
var $i = array (
  0 => 
  array (
    'selectfromstatement' => 's 1',
    'unionstatement' => 's 2',
    'expression' => 's 3',
    'SELECT' => 's 22',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
    'filterresult' => 's 118',
    '\'start\'' => 'a \'start\'',
  ),
  1 => 
  array (
    '\',\'' => 'r 2',
    '\')\'' => 'r 2',
    '#' => 'r 2',
  ),
  2 => 
  array (
    '\',\'' => 'r 3',
    '\')\'' => 'r 3',
    '#' => 'r 3',
  ),
  3 => 
  array (
    'UNION' => 's 4',
  ),
  4 => 
  array (
    'expression' => 's 5',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  5 => 
  array (
    '\',\'' => 'r 4',
    '\')\'' => 'r 4',
    '#' => 'r 4',
  ),
  6 => 
  array (
    'BETWEEN' => 's 7',
    'INNER' => 's 95',
    'LEFT' => 's 100',
    'RIGHT' => 's 105',
    'FULL' => 's 110',
    'LIKE' => 's 115',
    'UNION' => 'r 23',
    '\',\'' => 'r 23',
    '\')\'' => 'r 23',
    'AS' => 'r 23',
    'name' => 'r 23',
    'FROM' => 'r 23',
    'WHERE' => 'r 23',
    'GROUP' => 'r 23',
    '#' => 'r 23',
  ),
  7 => 
  array (
    'expressionD' => 's 8',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  8 => 
  array (
    'AND' => 's 9',
  ),
  9 => 
  array (
    'expressionD' => 's 10',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  10 => 
  array (
    'UNION' => 'r 24',
    '\',\'' => 'r 24',
    '\')\'' => 'r 24',
    'AS' => 'r 24',
    'name' => 'r 24',
    'FROM' => 'r 24',
    'WHERE' => 'r 24',
    'GROUP' => 'r 24',
    '#' => 'r 24',
  ),
  11 => 
  array (
    '\'+\'' => 's 12',
    '\'-\'' => 's 93',
    '\'<\'' => 'r 44',
    '\'>\'' => 'r 44',
    '\'=\'' => 'r 44',
    'AND' => 'r 44',
    'OR' => 'r 44',
    'LIKE' => 'r 44',
    'FULL' => 'r 44',
    'RIGHT' => 'r 44',
    'LEFT' => 'r 44',
    'INNER' => 'r 44',
    'BETWEEN' => 'r 44',
    'UNION' => 'r 44',
    '\',\'' => 'r 44',
    '\')\'' => 'r 44',
    'AS' => 'r 44',
    'name' => 'r 44',
    'FROM' => 'r 44',
    'WHERE' => 'r 44',
    'GROUP' => 'r 44',
    'ON' => 'r 44',
    '#' => 'r 44',
  ),
  12 => 
  array (
    'expressionE' => 's 11',
    'expressionD' => 's 13',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  13 => 
  array (
    '\'<\'' => 'r 42',
    '\'>\'' => 'r 42',
    '\'=\'' => 'r 42',
    'AND' => 'r 42',
    'OR' => 'r 42',
    'LIKE' => 'r 42',
    'FULL' => 'r 42',
    'RIGHT' => 'r 42',
    'LEFT' => 'r 42',
    'INNER' => 'r 42',
    'BETWEEN' => 'r 42',
    'UNION' => 'r 42',
    '\',\'' => 'r 42',
    '\')\'' => 'r 42',
    'AS' => 'r 42',
    'name' => 'r 42',
    'FROM' => 'r 42',
    'WHERE' => 'r 42',
    'GROUP' => 'r 42',
    'ON' => 'r 42',
    '#' => 'r 42',
  ),
  14 => 
  array (
    '\'*\'' => 's 15',
    '\'/\'' => 's 91',
    '\'-\'' => 'r 47',
    '\'+\'' => 'r 47',
    '\'<\'' => 'r 47',
    '\'>\'' => 'r 47',
    '\'=\'' => 'r 47',
    'AND' => 'r 47',
    'OR' => 'r 47',
    'LIKE' => 'r 47',
    'FULL' => 'r 47',
    'RIGHT' => 'r 47',
    'LEFT' => 'r 47',
    'INNER' => 'r 47',
    'BETWEEN' => 'r 47',
    'UNION' => 'r 47',
    '\',\'' => 'r 47',
    '\')\'' => 'r 47',
    'AS' => 'r 47',
    'name' => 'r 47',
    'FROM' => 'r 47',
    'WHERE' => 'r 47',
    'GROUP' => 'r 47',
    'ON' => 'r 47',
    '#' => 'r 47',
  ),
  15 => 
  array (
    'expressionF' => 's 14',
    'expressionE' => 's 16',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  16 => 
  array (
    '\'-\'' => 'r 45',
    '\'+\'' => 'r 45',
    '\'<\'' => 'r 45',
    '\'>\'' => 'r 45',
    '\'=\'' => 'r 45',
    'AND' => 'r 45',
    'OR' => 'r 45',
    'LIKE' => 'r 45',
    'FULL' => 'r 45',
    'RIGHT' => 'r 45',
    'LEFT' => 'r 45',
    'INNER' => 'r 45',
    'BETWEEN' => 'r 45',
    'UNION' => 'r 45',
    '\',\'' => 'r 45',
    '\')\'' => 'r 45',
    'AS' => 'r 45',
    'name' => 'r 45',
    'FROM' => 'r 45',
    'WHERE' => 'r 45',
    'GROUP' => 'r 45',
    'ON' => 'r 45',
    '#' => 'r 45',
  ),
  17 => 
  array (
    '\'/\'' => 'r 48',
    '\'*\'' => 'r 48',
    '\'-\'' => 'r 48',
    '\'+\'' => 'r 48',
    '\'<\'' => 'r 48',
    '\'>\'' => 'r 48',
    '\'=\'' => 'r 48',
    'AND' => 'r 48',
    'OR' => 'r 48',
    'LIKE' => 'r 48',
    'FULL' => 'r 48',
    'RIGHT' => 'r 48',
    'LEFT' => 'r 48',
    'INNER' => 'r 48',
    'BETWEEN' => 'r 48',
    'UNION' => 'r 48',
    '\',\'' => 'r 48',
    '\')\'' => 'r 48',
    'AS' => 'r 48',
    'name' => 'r 48',
    'FROM' => 'r 48',
    'WHERE' => 'r 48',
    'GROUP' => 'r 48',
    'ON' => 'r 48',
    '#' => 'r 48',
  ),
  18 => 
  array (
    '\'(\'' => 's 19',
    '\'/\'' => 'r 49',
    '\'*\'' => 'r 49',
    '\'-\'' => 'r 49',
    '\'+\'' => 'r 49',
    '\'<\'' => 'r 49',
    '\'>\'' => 'r 49',
    '\'=\'' => 'r 49',
    'AND' => 'r 49',
    'OR' => 'r 49',
    'LIKE' => 'r 49',
    'FULL' => 'r 49',
    'RIGHT' => 'r 49',
    'LEFT' => 'r 49',
    'INNER' => 'r 49',
    'BETWEEN' => 'r 49',
    'UNION' => 'r 49',
    '\',\'' => 'r 49',
    '\')\'' => 'r 49',
    'AS' => 'r 49',
    'name' => 'r 49',
    'FROM' => 'r 49',
    'WHERE' => 'r 49',
    'GROUP' => 'r 49',
    'ON' => 'r 49',
    '#' => 'r 49',
  ),
  19 => 
  array (
    'filterresult' => 's 20',
    'expression' => 's 21',
    'selectfromstatement' => 's 1',
    'unionstatement' => 's 2',
    'SELECT' => 's 22',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'statement' => 's 83',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  20 => 
  array (
    '\',\'' => 'r 0',
    '\')\'' => 'r 0',
  ),
  21 => 
  array (
    'UNION' => 's 4',
    '\',\'' => 'r 1',
    '\')\'' => 'r 1',
  ),
  22 => 
  array (
    'uniquefilter' => 's 23',
    'DISTINCT' => 's 82',
    'IN' => 'r 7',
    '\'(\'' => 'r 7',
    'constant' => 'r 7',
    'name' => 'r 7',
    '\'*\'' => 'r 7',
  ),
  23 => 
  array (
    'selecttablelist' => 's 24',
    'listoftables' => 's 72',
    'expression' => 's 73',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  24 => 
  array (
    'FROM' => 's 25',
  ),
  25 => 
  array (
    'expression' => 's 26',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  26 => 
  array (
    'wherefilter' => 's 27',
    'WHERE' => 's 70',
    'GROUP' => 'r 9',
    '\',\'' => 'r 9',
    '\')\'' => 'r 9',
    '#' => 'r 9',
  ),
  27 => 
  array (
    'groupfilter' => 's 28',
    'GROUP' => 's 29',
    '\',\'' => 'r 11',
    '\')\'' => 'r 11',
    '#' => 'r 11',
  ),
  28 => 
  array (
    '\',\'' => 'r 5',
    '\')\'' => 'r 5',
    '#' => 'r 5',
  ),
  29 => 
  array (
    'BY' => 's 30',
  ),
  30 => 
  array (
    'identifierlist' => 's 31',
    'identifier' => 's 67',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  31 => 
  array (
    'havingfilter' => 's 32',
    'HAVING' => 's 33',
    '\',\'' => 'r 13',
    '\')\'' => 'r 13',
    '#' => 'r 13',
  ),
  32 => 
  array (
    '\',\'' => 'r 10',
    '\')\'' => 'r 10',
    '#' => 'r 10',
  ),
  33 => 
  array (
    'expression' => 's 34',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  34 => 
  array (
    '\',\'' => 'r 12',
    '\')\'' => 'r 12',
    '#' => 'r 12',
  ),
  35 => 
  array (
    '\'(\'' => 's 36',
  ),
  36 => 
  array (
    'constant' => 's 37',
    'constantlist' => 's 40',
  ),
  37 => 
  array (
    '\',\'' => 's 38',
    '\')\'' => 'r 19',
  ),
  38 => 
  array (
    'constant' => 's 37',
    'constantlist' => 's 39',
  ),
  39 => 
  array (
    '\')\'' => 'r 20',
  ),
  40 => 
  array (
    '\')\'' => 's 41',
  ),
  41 => 
  array (
    'UNION' => 'r 25',
    '\',\'' => 'r 25',
    '\')\'' => 'r 25',
    'AS' => 'r 25',
    'name' => 'r 25',
    'FROM' => 'r 25',
    'WHERE' => 'r 25',
    'GROUP' => 'r 25',
    '#' => 'r 25',
  ),
  42 => 
  array (
    'OR' => 's 43',
    'LIKE' => 'r 32',
    'FULL' => 'r 32',
    'RIGHT' => 'r 32',
    'LEFT' => 'r 32',
    'INNER' => 'r 32',
    'BETWEEN' => 'r 32',
    'UNION' => 'r 32',
    '\',\'' => 'r 32',
    '\')\'' => 'r 32',
    'AS' => 'r 32',
    'name' => 'r 32',
    'FROM' => 'r 32',
    'WHERE' => 'r 32',
    'GROUP' => 'r 32',
    'ON' => 'r 32',
    '#' => 'r 32',
  ),
  43 => 
  array (
    'expressionB' => 's 42',
    'expressionA' => 's 44',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  44 => 
  array (
    'LIKE' => 'r 31',
    'FULL' => 'r 31',
    'RIGHT' => 'r 31',
    'LEFT' => 'r 31',
    'INNER' => 'r 31',
    'BETWEEN' => 'r 31',
    'UNION' => 'r 31',
    '\',\'' => 'r 31',
    '\')\'' => 'r 31',
    'AS' => 'r 31',
    'name' => 'r 31',
    'FROM' => 'r 31',
    'WHERE' => 'r 31',
    'GROUP' => 'r 31',
    'ON' => 'r 31',
    '#' => 'r 31',
  ),
  45 => 
  array (
    'AND' => 's 46',
    'OR' => 'r 34',
    'LIKE' => 'r 34',
    'FULL' => 'r 34',
    'RIGHT' => 'r 34',
    'LEFT' => 'r 34',
    'INNER' => 'r 34',
    'BETWEEN' => 'r 34',
    'UNION' => 'r 34',
    '\',\'' => 'r 34',
    '\')\'' => 'r 34',
    'AS' => 'r 34',
    'name' => 'r 34',
    'FROM' => 'r 34',
    'WHERE' => 'r 34',
    'GROUP' => 'r 34',
    'ON' => 'r 34',
    '#' => 'r 34',
  ),
  46 => 
  array (
    'expressionC' => 's 45',
    'expressionB' => 's 47',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  47 => 
  array (
    'OR' => 'r 33',
    'LIKE' => 'r 33',
    'FULL' => 'r 33',
    'RIGHT' => 'r 33',
    'LEFT' => 'r 33',
    'INNER' => 'r 33',
    'BETWEEN' => 'r 33',
    'UNION' => 'r 33',
    '\',\'' => 'r 33',
    '\')\'' => 'r 33',
    'AS' => 'r 33',
    'name' => 'r 33',
    'FROM' => 'r 33',
    'WHERE' => 'r 33',
    'GROUP' => 'r 33',
    'ON' => 'r 33',
    '#' => 'r 33',
  ),
  48 => 
  array (
    '\'=\'' => 's 49',
    '\'<\'' => 's 57',
    '\'>\'' => 's 63',
    'AND' => 'r 41',
    'OR' => 'r 41',
    'LIKE' => 'r 41',
    'FULL' => 'r 41',
    'RIGHT' => 'r 41',
    'LEFT' => 'r 41',
    'INNER' => 'r 41',
    'BETWEEN' => 'r 41',
    'UNION' => 'r 41',
    '\',\'' => 'r 41',
    '\')\'' => 'r 41',
    'AS' => 'r 41',
    'name' => 'r 41',
    'FROM' => 'r 41',
    'WHERE' => 'r 41',
    'GROUP' => 'r 41',
    'ON' => 'r 41',
    '#' => 'r 41',
  ),
  49 => 
  array (
    'expressionD' => 's 50',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  50 => 
  array (
    'AND' => 'r 35',
    'OR' => 'r 35',
    'LIKE' => 'r 35',
    'FULL' => 'r 35',
    'RIGHT' => 'r 35',
    'LEFT' => 'r 35',
    'INNER' => 'r 35',
    'BETWEEN' => 'r 35',
    'UNION' => 'r 35',
    '\',\'' => 'r 35',
    '\')\'' => 'r 35',
    'AS' => 'r 35',
    'name' => 'r 35',
    'FROM' => 'r 35',
    'WHERE' => 'r 35',
    'GROUP' => 'r 35',
    'ON' => 'r 35',
    '#' => 'r 35',
  ),
  51 => 
  array (
    'filterresult' => 's 20',
    'expression' => 's 21',
    'selectfromstatement' => 's 1',
    'unionstatement' => 's 2',
    'SELECT' => 's 22',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'statement' => 's 52',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  52 => 
  array (
    '\')\'' => 's 53',
  ),
  53 => 
  array (
    '\'/\'' => 'r 50',
    '\'*\'' => 'r 50',
    '\'-\'' => 'r 50',
    '\'+\'' => 'r 50',
    '\'<\'' => 'r 50',
    '\'>\'' => 'r 50',
    '\'=\'' => 'r 50',
    'AND' => 'r 50',
    'OR' => 'r 50',
    'LIKE' => 'r 50',
    'FULL' => 'r 50',
    'RIGHT' => 'r 50',
    'LEFT' => 'r 50',
    'INNER' => 'r 50',
    'BETWEEN' => 'r 50',
    'UNION' => 'r 50',
    '\',\'' => 'r 50',
    '\')\'' => 'r 50',
    'AS' => 'r 50',
    'name' => 'r 50',
    'FROM' => 'r 50',
    'WHERE' => 'r 50',
    'GROUP' => 'r 50',
    'ON' => 'r 50',
    '#' => 'r 50',
  ),
  54 => 
  array (
    '\'/\'' => 'r 51',
    '\'*\'' => 'r 51',
    '\'-\'' => 'r 51',
    '\'+\'' => 'r 51',
    '\'<\'' => 'r 51',
    '\'>\'' => 'r 51',
    '\'=\'' => 'r 51',
    'AND' => 'r 51',
    'OR' => 'r 51',
    'LIKE' => 'r 51',
    'FULL' => 'r 51',
    'RIGHT' => 'r 51',
    'LEFT' => 'r 51',
    'INNER' => 'r 51',
    'BETWEEN' => 'r 51',
    'UNION' => 'r 51',
    '\',\'' => 'r 51',
    '\')\'' => 'r 51',
    'AS' => 'r 51',
    'name' => 'r 51',
    'FROM' => 'r 51',
    'WHERE' => 'r 51',
    'GROUP' => 'r 51',
    'ON' => 'r 51',
    '#' => 'r 51',
  ),
  55 => 
  array (
    '\'(\'' => 'r 59',
    '\'/\'' => 'r 59',
    '\'*\'' => 'r 59',
    '\'-\'' => 'r 59',
    '\'+\'' => 'r 59',
    '\'<\'' => 'r 59',
    '\'>\'' => 'r 59',
    '\'=\'' => 'r 59',
    'AND' => 'r 59',
    'OR' => 'r 59',
    'LIKE' => 'r 59',
    'FULL' => 'r 59',
    'RIGHT' => 'r 59',
    'LEFT' => 'r 59',
    'INNER' => 'r 59',
    'BETWEEN' => 'r 59',
    'UNION' => 'r 59',
    '\',\'' => 'r 59',
    '\')\'' => 'r 59',
    'AS' => 'r 59',
    'name' => 'r 59',
    'FROM' => 'r 59',
    'WHERE' => 'r 59',
    'GROUP' => 'r 59',
    'HAVING' => 'r 59',
    'ON' => 'r 59',
    '#' => 'r 59',
  ),
  56 => 
  array (
    '\'(\'' => 'r 60',
    '\'/\'' => 'r 60',
    '\'*\'' => 'r 60',
    '\'-\'' => 'r 60',
    '\'+\'' => 'r 60',
    '\'<\'' => 'r 60',
    '\'>\'' => 'r 60',
    '\'=\'' => 'r 60',
    'AND' => 'r 60',
    'OR' => 'r 60',
    'LIKE' => 'r 60',
    'FULL' => 'r 60',
    'RIGHT' => 'r 60',
    'LEFT' => 'r 60',
    'INNER' => 'r 60',
    'BETWEEN' => 'r 60',
    'UNION' => 'r 60',
    '\',\'' => 'r 60',
    '\')\'' => 'r 60',
    'AS' => 'r 60',
    'name' => 'r 60',
    'FROM' => 'r 60',
    'WHERE' => 'r 60',
    'GROUP' => 'r 60',
    'HAVING' => 'r 60',
    'ON' => 'r 60',
    '#' => 'r 60',
  ),
  57 => 
  array (
    'expressionD' => 's 58',
    '\'=\'' => 's 59',
    '\'>\'' => 's 61',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  58 => 
  array (
    'AND' => 'r 36',
    'OR' => 'r 36',
    'LIKE' => 'r 36',
    'FULL' => 'r 36',
    'RIGHT' => 'r 36',
    'LEFT' => 'r 36',
    'INNER' => 'r 36',
    'BETWEEN' => 'r 36',
    'UNION' => 'r 36',
    '\',\'' => 'r 36',
    '\')\'' => 'r 36',
    'AS' => 'r 36',
    'name' => 'r 36',
    'FROM' => 'r 36',
    'WHERE' => 'r 36',
    'GROUP' => 'r 36',
    'ON' => 'r 36',
    '#' => 'r 36',
  ),
  59 => 
  array (
    'expressionD' => 's 60',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  60 => 
  array (
    'AND' => 'r 38',
    'OR' => 'r 38',
    'LIKE' => 'r 38',
    'FULL' => 'r 38',
    'RIGHT' => 'r 38',
    'LEFT' => 'r 38',
    'INNER' => 'r 38',
    'BETWEEN' => 'r 38',
    'UNION' => 'r 38',
    '\',\'' => 'r 38',
    '\')\'' => 'r 38',
    'AS' => 'r 38',
    'name' => 'r 38',
    'FROM' => 'r 38',
    'WHERE' => 'r 38',
    'GROUP' => 'r 38',
    'ON' => 'r 38',
    '#' => 'r 38',
  ),
  61 => 
  array (
    'expressionD' => 's 62',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  62 => 
  array (
    'AND' => 'r 40',
    'OR' => 'r 40',
    'LIKE' => 'r 40',
    'FULL' => 'r 40',
    'RIGHT' => 'r 40',
    'LEFT' => 'r 40',
    'INNER' => 'r 40',
    'BETWEEN' => 'r 40',
    'UNION' => 'r 40',
    '\',\'' => 'r 40',
    '\')\'' => 'r 40',
    'AS' => 'r 40',
    'name' => 'r 40',
    'FROM' => 'r 40',
    'WHERE' => 'r 40',
    'GROUP' => 'r 40',
    'ON' => 'r 40',
    '#' => 'r 40',
  ),
  63 => 
  array (
    'expressionD' => 's 64',
    '\'=\'' => 's 65',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  64 => 
  array (
    'AND' => 'r 37',
    'OR' => 'r 37',
    'LIKE' => 'r 37',
    'FULL' => 'r 37',
    'RIGHT' => 'r 37',
    'LEFT' => 'r 37',
    'INNER' => 'r 37',
    'BETWEEN' => 'r 37',
    'UNION' => 'r 37',
    '\',\'' => 'r 37',
    '\')\'' => 'r 37',
    'AS' => 'r 37',
    'name' => 'r 37',
    'FROM' => 'r 37',
    'WHERE' => 'r 37',
    'GROUP' => 'r 37',
    'ON' => 'r 37',
    '#' => 'r 37',
  ),
  65 => 
  array (
    'expressionD' => 's 66',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  66 => 
  array (
    'AND' => 'r 39',
    'OR' => 'r 39',
    'LIKE' => 'r 39',
    'FULL' => 'r 39',
    'RIGHT' => 'r 39',
    'LEFT' => 'r 39',
    'INNER' => 'r 39',
    'BETWEEN' => 'r 39',
    'UNION' => 'r 39',
    '\',\'' => 'r 39',
    '\')\'' => 'r 39',
    'AS' => 'r 39',
    'name' => 'r 39',
    'FROM' => 'r 39',
    'WHERE' => 'r 39',
    'GROUP' => 'r 39',
    'ON' => 'r 39',
    '#' => 'r 39',
  ),
  67 => 
  array (
    '\',\'' => 's 68',
    'HAVING' => 'r 56',
    '\')\'' => 'r 56',
    '#' => 'r 56',
  ),
  68 => 
  array (
    'identifier' => 's 67',
    'identifierlist' => 's 69',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  69 => 
  array (
    'HAVING' => 'r 57',
    '\',\'' => 'r 57',
    '\')\'' => 'r 57',
    '#' => 'r 57',
  ),
  70 => 
  array (
    'expression' => 's 71',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  71 => 
  array (
    'GROUP' => 'r 8',
    '\',\'' => 'r 8',
    '\')\'' => 'r 8',
    '#' => 'r 8',
  ),
  72 => 
  array (
    'FROM' => 'r 14',
  ),
  73 => 
  array (
    'asopt' => 's 74',
    '\',\'' => 's 79',
    'AS' => 's 81',
    'FROM' => 'r 15',
    'name' => 'r 22',
  ),
  74 => 
  array (
    'allowedalias' => 's 75',
    'name' => 's 78',
  ),
  75 => 
  array (
    '\',\'' => 's 76',
    'FROM' => 'r 16',
  ),
  76 => 
  array (
    'expression' => 's 73',
    'listoftables' => 's 77',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  77 => 
  array (
    'FROM' => 'r 18',
  ),
  78 => 
  array (
    '\',\'' => 'r 58',
    'FROM' => 'r 58',
  ),
  79 => 
  array (
    'expression' => 's 73',
    'listoftables' => 's 80',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  80 => 
  array (
    'FROM' => 'r 17',
  ),
  81 => 
  array (
    'name' => 'r 21',
  ),
  82 => 
  array (
    'IN' => 'r 6',
    '\'(\'' => 'r 6',
    'constant' => 'r 6',
    'name' => 'r 6',
    '\'*\'' => 'r 6',
  ),
  83 => 
  array (
    '\')\'' => 's 84',
    '\',\'' => 's 85',
  ),
  84 => 
  array (
    '\'/\'' => 'r 52',
    '\'*\'' => 'r 52',
    '\'-\'' => 'r 52',
    '\'+\'' => 'r 52',
    '\'<\'' => 'r 52',
    '\'>\'' => 'r 52',
    '\'=\'' => 'r 52',
    'AND' => 'r 52',
    'OR' => 'r 52',
    'LIKE' => 'r 52',
    'FULL' => 'r 52',
    'RIGHT' => 'r 52',
    'LEFT' => 'r 52',
    'INNER' => 'r 52',
    'BETWEEN' => 'r 52',
    'UNION' => 'r 52',
    '\',\'' => 'r 52',
    '\')\'' => 'r 52',
    'AS' => 'r 52',
    'name' => 'r 52',
    'FROM' => 'r 52',
    'WHERE' => 'r 52',
    'GROUP' => 'r 52',
    'ON' => 'r 52',
    '#' => 'r 52',
  ),
  85 => 
  array (
    'filterresult' => 's 20',
    'expression' => 's 21',
    'selectfromstatement' => 's 1',
    'unionstatement' => 's 2',
    'SELECT' => 's 22',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'statement' => 's 86',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  86 => 
  array (
    '\')\'' => 's 87',
    '\',\'' => 's 88',
  ),
  87 => 
  array (
    '\'/\'' => 'r 53',
    '\'*\'' => 'r 53',
    '\'-\'' => 'r 53',
    '\'+\'' => 'r 53',
    '\'<\'' => 'r 53',
    '\'>\'' => 'r 53',
    '\'=\'' => 'r 53',
    'AND' => 'r 53',
    'OR' => 'r 53',
    'LIKE' => 'r 53',
    'FULL' => 'r 53',
    'RIGHT' => 'r 53',
    'LEFT' => 'r 53',
    'INNER' => 'r 53',
    'BETWEEN' => 'r 53',
    'UNION' => 'r 53',
    '\',\'' => 'r 53',
    '\')\'' => 'r 53',
    'AS' => 'r 53',
    'name' => 'r 53',
    'FROM' => 'r 53',
    'WHERE' => 'r 53',
    'GROUP' => 'r 53',
    'ON' => 'r 53',
    '#' => 'r 53',
  ),
  88 => 
  array (
    'filterresult' => 's 20',
    'expression' => 's 21',
    'selectfromstatement' => 's 1',
    'unionstatement' => 's 2',
    'SELECT' => 's 22',
    'expressionA' => 's 6',
    'IN' => 's 35',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'statement' => 's 89',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  89 => 
  array (
    '\')\'' => 's 90',
  ),
  90 => 
  array (
    '\'/\'' => 'r 54',
    '\'*\'' => 'r 54',
    '\'-\'' => 'r 54',
    '\'+\'' => 'r 54',
    '\'<\'' => 'r 54',
    '\'>\'' => 'r 54',
    '\'=\'' => 'r 54',
    'AND' => 'r 54',
    'OR' => 'r 54',
    'LIKE' => 'r 54',
    'FULL' => 'r 54',
    'RIGHT' => 'r 54',
    'LEFT' => 'r 54',
    'INNER' => 'r 54',
    'BETWEEN' => 'r 54',
    'UNION' => 'r 54',
    '\',\'' => 'r 54',
    '\')\'' => 'r 54',
    'AS' => 'r 54',
    'name' => 'r 54',
    'FROM' => 'r 54',
    'WHERE' => 'r 54',
    'GROUP' => 'r 54',
    'ON' => 'r 54',
    '#' => 'r 54',
  ),
  91 => 
  array (
    'expressionF' => 's 14',
    'expressionE' => 's 92',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  92 => 
  array (
    '\'-\'' => 'r 46',
    '\'+\'' => 'r 46',
    '\'<\'' => 'r 46',
    '\'>\'' => 'r 46',
    '\'=\'' => 'r 46',
    'AND' => 'r 46',
    'OR' => 'r 46',
    'LIKE' => 'r 46',
    'FULL' => 'r 46',
    'RIGHT' => 'r 46',
    'LEFT' => 'r 46',
    'INNER' => 'r 46',
    'BETWEEN' => 'r 46',
    'UNION' => 'r 46',
    '\',\'' => 'r 46',
    '\')\'' => 'r 46',
    'AS' => 'r 46',
    'name' => 'r 46',
    'FROM' => 'r 46',
    'WHERE' => 'r 46',
    'GROUP' => 'r 46',
    'ON' => 'r 46',
    '#' => 'r 46',
  ),
  93 => 
  array (
    'expressionE' => 's 11',
    'expressionD' => 's 94',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  94 => 
  array (
    '\'<\'' => 'r 43',
    '\'>\'' => 'r 43',
    '\'=\'' => 'r 43',
    'AND' => 'r 43',
    'OR' => 'r 43',
    'LIKE' => 'r 43',
    'FULL' => 'r 43',
    'RIGHT' => 'r 43',
    'LEFT' => 'r 43',
    'INNER' => 'r 43',
    'BETWEEN' => 'r 43',
    'UNION' => 'r 43',
    '\',\'' => 'r 43',
    '\')\'' => 'r 43',
    'AS' => 'r 43',
    'name' => 'r 43',
    'FROM' => 'r 43',
    'WHERE' => 'r 43',
    'GROUP' => 'r 43',
    'ON' => 'r 43',
    '#' => 'r 43',
  ),
  95 => 
  array (
    'JOIN' => 's 96',
  ),
  96 => 
  array (
    'expressionA' => 's 97',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  97 => 
  array (
    'ON' => 's 98',
  ),
  98 => 
  array (
    'expressionA' => 's 99',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  99 => 
  array (
    'UNION' => 'r 26',
    '\',\'' => 'r 26',
    '\')\'' => 'r 26',
    'AS' => 'r 26',
    'name' => 'r 26',
    'FROM' => 'r 26',
    'WHERE' => 'r 26',
    'GROUP' => 'r 26',
    '#' => 'r 26',
  ),
  100 => 
  array (
    'JOIN' => 's 101',
  ),
  101 => 
  array (
    'expressionA' => 's 102',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  102 => 
  array (
    'ON' => 's 103',
  ),
  103 => 
  array (
    'expressionA' => 's 104',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  104 => 
  array (
    'UNION' => 'r 27',
    '\',\'' => 'r 27',
    '\')\'' => 'r 27',
    'AS' => 'r 27',
    'name' => 'r 27',
    'FROM' => 'r 27',
    'WHERE' => 'r 27',
    'GROUP' => 'r 27',
    '#' => 'r 27',
  ),
  105 => 
  array (
    'JOIN' => 's 106',
  ),
  106 => 
  array (
    'expressionA' => 's 107',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  107 => 
  array (
    'ON' => 's 108',
  ),
  108 => 
  array (
    'expressionA' => 's 109',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  109 => 
  array (
    'UNION' => 'r 28',
    '\',\'' => 'r 28',
    '\')\'' => 'r 28',
    'AS' => 'r 28',
    'name' => 'r 28',
    'FROM' => 'r 28',
    'WHERE' => 'r 28',
    'GROUP' => 'r 28',
    '#' => 'r 28',
  ),
  110 => 
  array (
    'JOIN' => 's 111',
  ),
  111 => 
  array (
    'expressionA' => 's 112',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  112 => 
  array (
    'ON' => 's 113',
  ),
  113 => 
  array (
    'expressionA' => 's 114',
    'expressionB' => 's 42',
    'expressionC' => 's 45',
    'expressionD' => 's 48',
    'expressionE' => 's 11',
    'expressionF' => 's 14',
    'endexpression' => 's 17',
    'identifier' => 's 18',
    '\'(\'' => 's 51',
    'constant' => 's 54',
    'name' => 's 55',
    '\'*\'' => 's 56',
  ),
  114 => 
  array (
    'UNION' => 'r 29',
    '\',\'' => 'r 29',
    '\')\'' => 'r 29',
    'AS' => 'r 29',
    'name' => 'r 29',
    'FROM' => 'r 29',
    'WHERE' => 'r 29',
    'GROUP' => 'r 29',
    '#' => 'r 29',
  ),
  115 => 
  array (
    'likeexpression' => 's 116',
    'constant' => 's 117',
  ),
  116 => 
  array (
    'UNION' => 'r 30',
    '\',\'' => 'r 30',
    '\')\'' => 'r 30',
    'AS' => 'r 30',
    'name' => 'r 30',
    'FROM' => 'r 30',
    'WHERE' => 'r 30',
    'GROUP' => 'r 30',
    '#' => 'r 30',
  ),
  117 => 
  array (
    'UNION' => 'r 55',
    '\',\'' => 'r 55',
    '\')\'' => 'r 55',
    'AS' => 'r 55',
    'name' => 'r 55',
    'FROM' => 'r 55',
    'WHERE' => 'r 55',
    'GROUP' => 'r 55',
    '#' => 'r 55',
  ),
  118 => 
  array (
    '#' => 'r 61',
  ),
);
function reduce_0_statement_1($tokens, &$result) {
#
# (0) statement :=  filterresult
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_1_statement_2($tokens, &$result) {
#
# (1) statement :=  expression
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_2_filterresult_1($tokens, &$result) {
#
# (2) filterresult :=  selectfromstatement
#
$result = reset($tokens);
$result = $tokens[0];/*TODO*/
}

function reduce_3_filterresult_2($tokens, &$result) {
#
# (3) filterresult :=  unionstatement
#
$result = reset($tokens);
$result = $tokens[0];/*TODO*/
}

function reduce_4_unionstatement_1($tokens, &$result) {
#
# (4) unionstatement :=  expression  UNION  expression
#
$result = reset($tokens);
$expr1 =& $tokens[0];
$expr2 =& $tokens[2];
$result = null;/*TODO*/
}

function reduce_5_selectfromstatement_1($tokens, &$result) {
#
# (5) selectfromstatement :=  SELECT  uniquefilter  selecttablelist  FROM  expression  wherefilter  groupfilter
#
$result = reset($tokens);
$distinct =& $tokens[1];
$selecttables =& $tokens[2];
$fromtable =& $tokens[4];
$where =& $tokens[5];
$groupby =& $tokens[6];
// 1) fromtables
                         // 2) wherefilter (if defined)
                         // 3) groupbyfilter (if defined)
                         // 4) selecttables (if not '*')
                         // 5) distinctfilter (if defined)
                        
                        $totalfilter=$fromtable;
                        $totalfilter=putFilterAfterIfExists($totalfilter, $where);
                        $totalfilter=putFilterAfterIfExists($totalfilter, $groupby);
                        $totalfilter=putFilterAfterIfExists($totalfilter, $selecttables);
                        $totalfilter=putFilterAfterIfExists($totalfilter, $distinct);
                        
                        $result=$totalfilter;
}

function reduce_6_uniquefilter_1($tokens, &$result) {
#
# (6) uniquefilter :=  DISTINCT
#
$result = reset($tokens);
$result = new DistinctFilter();
}

function reduce_7_uniquefilter_2($tokens, &$result) {
#
# (7) uniquefilter :=
#
$result = reset($tokens);
$result = null;
}

function reduce_8_wherefilter_1($tokens, &$result) {
#
# (8) wherefilter :=  WHERE  expression
#
$result = reset($tokens);
$expr =& $tokens[1];
$result = new FilterByExpressionFilter($expr);
}

function reduce_9_wherefilter_2($tokens, &$result) {
#
# (9) wherefilter :=
#
$result = reset($tokens);
$result = null;
}

function reduce_10_groupfilter_1($tokens, &$result) {
#
# (10) groupfilter :=  GROUP  BY  identifierlist  havingfilter
#
$result = reset($tokens);
$groupFields =& $tokens[2];
$having =& $tokens[3];
$result = putFilterAfterIfExists(new DataGrouper($groupFields), $having);
}

function reduce_11_groupfilter_2($tokens, &$result) {
#
# (11) groupfilter :=
#
$result = reset($tokens);
$result = null;
}

function reduce_12_havingfilter_1($tokens, &$result) {
#
# (12) havingfilter :=  HAVING  expression
#
$result = reset($tokens);
$expr =& $tokens[1];
$result = new FilterByExpressionFilter($expr);
}

function reduce_13_havingfilter_2($tokens, &$result) {
#
# (13) havingfilter :=
#
$result = reset($tokens);
$result = null;
}

function reduce_14_selecttablelist_1($tokens, &$result) {
#
# (14) selecttablelist :=  listoftables
#
$result = reset($tokens);
$result = new ColumnSelectionFilter($tokens[0]);
}

function reduce_15_listoftables_1($tokens, &$result) {
#
# (15) listoftables :=  expression
#
$result = reset($tokens);
$expr =& $tokens[0];
$result = array(new ColumnSelectionFilterColumn($expr, null));
}

function reduce_16_listoftables_2($tokens, &$result) {
#
# (16) listoftables :=  expression  asopt  allowedalias
#
$result = reset($tokens);
$expr =& $tokens[0];
$alias =& $tokens[2];
$result = array(new ColumnSelectionFilterColumn($expr, $alias));
}

function reduce_17_listoftables_3($tokens, &$result) {
#
# (17) listoftables :=  expression  ','  listoftables
#
$result = reset($tokens);
$expr =& $tokens[0];
$arr =& $tokens[2];
array_unshift($arr, new ColumnSelectionFilterColumn($expr, null));$result = $arr;
}

function reduce_18_listoftables_4($tokens, &$result) {
#
# (18) listoftables :=  expression  asopt  allowedalias  ','  listoftables
#
$result = reset($tokens);
$expr =& $tokens[0];
$alias =& $tokens[2];
$arr =& $tokens[4];
array_unshift($arr, new ColumnSelectionFilterColumn($expr, $alias));$result = $arr;
}

function reduce_19_constantlist_1($tokens, &$result) {
#
# (19) constantlist :=  constant
#
$result = reset($tokens);
$result = array(new Constant($tokens[0]));
}

function reduce_20_constantlist_2($tokens, &$result) {
#
# (20) constantlist :=  constant  ','  constantlist
#
$result = reset($tokens);
$arr =& $tokens[2];
array_unshift($arr, $tokens[0]);$result = $arr;
}

function reduce_21_asopt_1($tokens, &$result) {
#
# (21) asopt :=  AS
#
$result = reset($tokens);

}

function reduce_22_asopt_2($tokens, &$result) {
#
# (22) asopt :=
#
$result = reset($tokens);

}

function reduce_23_expression_1($tokens, &$result) {
#
# (23) expression :=  expressionA
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_24_expression_2($tokens, &$result) {
#
# (24) expression :=  expressionA  BETWEEN  expressionD  AND  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$c =& $tokens[4];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_AND, 
                                    new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_OR_EQUAL_THAN, $b, $a), 
                                    new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_OR_EQUAL_THAN, $a, $c));
}

function reduce_25_expression_3($tokens, &$result) {
#
# (25) expression :=  IN  '('  constantlist  ')'
#
$result = reset($tokens);
$constantlist =& $tokens[2];
$result = new CheckInFunction($constantlist);
}

function reduce_26_expression_4($tokens, &$result) {
#
# (26) expression :=  expressionA  INNER  JOIN  expressionA  ON  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$c =& $tokens[5];
$result = null;/*TODO*/
}

function reduce_27_expression_5($tokens, &$result) {
#
# (27) expression :=  expressionA  LEFT  JOIN  expressionA  ON  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$c =& $tokens[5];
$result = null;/*TODO*/
}

function reduce_28_expression_6($tokens, &$result) {
#
# (28) expression :=  expressionA  RIGHT  JOIN  expressionA  ON  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$c =& $tokens[5];
$result = null;/*TODO*/
}

function reduce_29_expression_7($tokens, &$result) {
#
# (29) expression :=  expressionA  FULL  JOIN  expressionA  ON  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$c =& $tokens[5];
$result = null;/*TODO*/
}

function reduce_30_expression_8($tokens, &$result) {
#
# (30) expression :=  expressionA  LIKE  likeexpression
#
$result = reset($tokens);
$expr =& $tokens[0];
$likeexpr =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_UNAIRY_MATCH_REGEX, $expr, convertRegexFromSQLToUniversal($likeexpr));
}

function reduce_31_expressionA_1($tokens, &$result) {
#
# (31) expressionA :=  expressionB  OR  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_OR, $a, $b);
}

function reduce_32_expressionA_2($tokens, &$result) {
#
# (32) expressionA :=  expressionB
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_33_expressionB_1($tokens, &$result) {
#
# (33) expressionB :=  expressionC  AND  expressionB
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_AND, $a, $b);
}

function reduce_34_expressionB_2($tokens, &$result) {
#
# (34) expressionB :=  expressionC
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_35_expressionC_1($tokens, &$result) {
#
# (35) expressionC :=  expressionD  '='  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_EQUAL, $a, $b);
}

function reduce_36_expressionC_2($tokens, &$result) {
#
# (36) expressionC :=  expressionD  '<'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_THAN, $a, $b);
}

function reduce_37_expressionC_3($tokens, &$result) {
#
# (37) expressionC :=  expressionD  '>'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_LARGER_THAN, $a, $b);
}

function reduce_38_expressionC_4($tokens, &$result) {
#
# (38) expressionC :=  expressionD  '<'  '='  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_OR_EQUAL_THAN, $a, $b);
}

function reduce_39_expressionC_5($tokens, &$result) {
#
# (39) expressionC :=  expressionD  '>'  '='  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_LARGER_OR_EQUAL_THAN, $a, $b);
}

function reduce_40_expressionC_6($tokens, &$result) {
#
# (40) expressionC :=  expressionD  '<'  '>'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_NOTEQUAL, $a, $b);
}

function reduce_41_expressionC_7($tokens, &$result) {
#
# (41) expressionC :=  expressionD
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_42_expressionD_1($tokens, &$result) {
#
# (42) expressionD :=  expressionE  '+'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_PLUS, $a, $b);
}

function reduce_43_expressionD_2($tokens, &$result) {
#
# (43) expressionD :=  expressionE  '-'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_MINUS, $a, $b);
}

function reduce_44_expressionD_3($tokens, &$result) {
#
# (44) expressionD :=  expressionE
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_45_expressionE_1($tokens, &$result) {
#
# (45) expressionE :=  expressionF  '*'  expressionE
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_MULTIPLY, $a, $b);
}

function reduce_46_expressionE_2($tokens, &$result) {
#
# (46) expressionE :=  expressionF  '/'  expressionE
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_DIVIDE, $a, $b);
}

function reduce_47_expressionE_3($tokens, &$result) {
#
# (47) expressionE :=  expressionF
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_48_expressionF_1($tokens, &$result) {
#
# (48) expressionF :=  endexpression
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_49_endexpression_1($tokens, &$result) {
#
# (49) endexpression :=  identifier
#
$result = reset($tokens);
$result = new Identifier($tokens[0]);
}

function reduce_50_endexpression_2($tokens, &$result) {
#
# (50) endexpression :=  '('  statement  ')'
#
$result = reset($tokens);
$stat =& $tokens[1];
$result = $stat;
}

function reduce_51_endexpression_3($tokens, &$result) {
#
# (51) endexpression :=  constant
#
$result = reset($tokens);
$result = new Constant($tokens[0]);
}

function reduce_52_endexpression_4($tokens, &$result) {
#
# (52) endexpression :=  identifier  '('  statement  ')'
#
$result = reset($tokens);
$functid =& $tokens[0];
$arg1 =& $tokens[2];
$result = getUnaryFilterForSQLFunction($functid, $arg1);
}

function reduce_53_endexpression_5($tokens, &$result) {
#
# (53) endexpression :=  identifier  '('  statement  ','  statement  ')'
#
$result = reset($tokens);
$functid =& $tokens[0];
$arg1 =& $tokens[2];
$arg2 =& $tokens[4];
$result = getBinaryFunctionForSQLFunction($functid, $arg1, $arg2);
}

function reduce_54_endexpression_6($tokens, &$result) {
#
# (54) endexpression :=  identifier  '('  statement  ','  statement  ','  statement  ')'
#
$result = reset($tokens);
$functid =& $tokens[0];
$arg1 =& $tokens[2];
$arg2 =& $tokens[4];
$arg3 =& $tokens[6];
$result =getTertairyFunctionForSQLFunction($functid, $arg1, $arg2, $arg3);
}

function reduce_55_likeexpression_1($tokens, &$result) {
#
# (55) likeexpression :=  constant
#
$result = reset($tokens);
$result = new Constant($tokens[0]);
}

function reduce_56_identifierlist_1($tokens, &$result) {
#
# (56) identifierlist :=  identifier
#
$result = reset($tokens);
$result = array(new Identifier($tokens[0]));
}

function reduce_57_identifierlist_2($tokens, &$result) {
#
# (57) identifierlist :=  identifier  ','  identifierlist
#
$result = reset($tokens);
$arr =& $tokens[2];
array_unshift($arr, new Identifier($tokens[0]));$result=$arr;
}

function reduce_58_allowedalias_1($tokens, &$result) {
#
# (58) allowedalias :=  name
#
$result = reset($tokens);
$result=$tokens[0];
}

function reduce_59_identifier_1($tokens, &$result) {
#
# (59) identifier :=  name
#
$result = reset($tokens);
$result=$tokens[0];
}

function reduce_60_identifier_2($tokens, &$result) {
#
# (60) identifier :=  '*'
#
$result = reset($tokens);
$result="*";
}

function reduce_61_start_1($tokens, &$result) {
#
# (61) 'start' :=  filterresult
#
$result = reset($tokens);

}

var $method = array (
  0 => 'reduce_0_statement_1',
  1 => 'reduce_1_statement_2',
  2 => 'reduce_2_filterresult_1',
  3 => 'reduce_3_filterresult_2',
  4 => 'reduce_4_unionstatement_1',
  5 => 'reduce_5_selectfromstatement_1',
  6 => 'reduce_6_uniquefilter_1',
  7 => 'reduce_7_uniquefilter_2',
  8 => 'reduce_8_wherefilter_1',
  9 => 'reduce_9_wherefilter_2',
  10 => 'reduce_10_groupfilter_1',
  11 => 'reduce_11_groupfilter_2',
  12 => 'reduce_12_havingfilter_1',
  13 => 'reduce_13_havingfilter_2',
  14 => 'reduce_14_selecttablelist_1',
  15 => 'reduce_15_listoftables_1',
  16 => 'reduce_16_listoftables_2',
  17 => 'reduce_17_listoftables_3',
  18 => 'reduce_18_listoftables_4',
  19 => 'reduce_19_constantlist_1',
  20 => 'reduce_20_constantlist_2',
  21 => 'reduce_21_asopt_1',
  22 => 'reduce_22_asopt_2',
  23 => 'reduce_23_expression_1',
  24 => 'reduce_24_expression_2',
  25 => 'reduce_25_expression_3',
  26 => 'reduce_26_expression_4',
  27 => 'reduce_27_expression_5',
  28 => 'reduce_28_expression_6',
  29 => 'reduce_29_expression_7',
  30 => 'reduce_30_expression_8',
  31 => 'reduce_31_expressionA_1',
  32 => 'reduce_32_expressionA_2',
  33 => 'reduce_33_expressionB_1',
  34 => 'reduce_34_expressionB_2',
  35 => 'reduce_35_expressionC_1',
  36 => 'reduce_36_expressionC_2',
  37 => 'reduce_37_expressionC_3',
  38 => 'reduce_38_expressionC_4',
  39 => 'reduce_39_expressionC_5',
  40 => 'reduce_40_expressionC_6',
  41 => 'reduce_41_expressionC_7',
  42 => 'reduce_42_expressionD_1',
  43 => 'reduce_43_expressionD_2',
  44 => 'reduce_44_expressionD_3',
  45 => 'reduce_45_expressionE_1',
  46 => 'reduce_46_expressionE_2',
  47 => 'reduce_47_expressionE_3',
  48 => 'reduce_48_expressionF_1',
  49 => 'reduce_49_endexpression_1',
  50 => 'reduce_50_endexpression_2',
  51 => 'reduce_51_endexpression_3',
  52 => 'reduce_52_endexpression_4',
  53 => 'reduce_53_endexpression_5',
  54 => 'reduce_54_endexpression_6',
  55 => 'reduce_55_likeexpression_1',
  56 => 'reduce_56_identifierlist_1',
  57 => 'reduce_57_identifierlist_2',
  58 => 'reduce_58_allowedalias_1',
  59 => 'reduce_59_identifier_1',
  60 => 'reduce_60_identifier_2',
  61 => 'reduce_61_start_1',
);
var $a = array (
  0 => 
  array (
    'symbol' => 'statement',
    'len' => 1,
    'replace' => true,
  ),
  1 => 
  array (
    'symbol' => 'statement',
    'len' => 1,
    'replace' => true,
  ),
  2 => 
  array (
    'symbol' => 'filterresult',
    'len' => 1,
    'replace' => true,
  ),
  3 => 
  array (
    'symbol' => 'filterresult',
    'len' => 1,
    'replace' => true,
  ),
  4 => 
  array (
    'symbol' => 'unionstatement',
    'len' => 3,
    'replace' => true,
  ),
  5 => 
  array (
    'symbol' => 'selectfromstatement',
    'len' => 7,
    'replace' => true,
  ),
  6 => 
  array (
    'symbol' => 'uniquefilter',
    'len' => 1,
    'replace' => true,
  ),
  7 => 
  array (
    'symbol' => 'uniquefilter',
    'len' => 0,
    'replace' => true,
  ),
  8 => 
  array (
    'symbol' => 'wherefilter',
    'len' => 2,
    'replace' => true,
  ),
  9 => 
  array (
    'symbol' => 'wherefilter',
    'len' => 0,
    'replace' => true,
  ),
  10 => 
  array (
    'symbol' => 'groupfilter',
    'len' => 4,
    'replace' => true,
  ),
  11 => 
  array (
    'symbol' => 'groupfilter',
    'len' => 0,
    'replace' => true,
  ),
  12 => 
  array (
    'symbol' => 'havingfilter',
    'len' => 2,
    'replace' => true,
  ),
  13 => 
  array (
    'symbol' => 'havingfilter',
    'len' => 0,
    'replace' => true,
  ),
  14 => 
  array (
    'symbol' => 'selecttablelist',
    'len' => 1,
    'replace' => true,
  ),
  15 => 
  array (
    'symbol' => 'listoftables',
    'len' => 1,
    'replace' => true,
  ),
  16 => 
  array (
    'symbol' => 'listoftables',
    'len' => 3,
    'replace' => true,
  ),
  17 => 
  array (
    'symbol' => 'listoftables',
    'len' => 3,
    'replace' => true,
  ),
  18 => 
  array (
    'symbol' => 'listoftables',
    'len' => 5,
    'replace' => true,
  ),
  19 => 
  array (
    'symbol' => 'constantlist',
    'len' => 1,
    'replace' => true,
  ),
  20 => 
  array (
    'symbol' => 'constantlist',
    'len' => 3,
    'replace' => true,
  ),
  21 => 
  array (
    'symbol' => 'asopt',
    'len' => 1,
    'replace' => true,
  ),
  22 => 
  array (
    'symbol' => 'asopt',
    'len' => 0,
    'replace' => true,
  ),
  23 => 
  array (
    'symbol' => 'expression',
    'len' => 1,
    'replace' => true,
  ),
  24 => 
  array (
    'symbol' => 'expression',
    'len' => 5,
    'replace' => true,
  ),
  25 => 
  array (
    'symbol' => 'expression',
    'len' => 4,
    'replace' => true,
  ),
  26 => 
  array (
    'symbol' => 'expression',
    'len' => 6,
    'replace' => true,
  ),
  27 => 
  array (
    'symbol' => 'expression',
    'len' => 6,
    'replace' => true,
  ),
  28 => 
  array (
    'symbol' => 'expression',
    'len' => 6,
    'replace' => true,
  ),
  29 => 
  array (
    'symbol' => 'expression',
    'len' => 6,
    'replace' => true,
  ),
  30 => 
  array (
    'symbol' => 'expression',
    'len' => 3,
    'replace' => true,
  ),
  31 => 
  array (
    'symbol' => 'expressionA',
    'len' => 3,
    'replace' => true,
  ),
  32 => 
  array (
    'symbol' => 'expressionA',
    'len' => 1,
    'replace' => true,
  ),
  33 => 
  array (
    'symbol' => 'expressionB',
    'len' => 3,
    'replace' => true,
  ),
  34 => 
  array (
    'symbol' => 'expressionB',
    'len' => 1,
    'replace' => true,
  ),
  35 => 
  array (
    'symbol' => 'expressionC',
    'len' => 3,
    'replace' => true,
  ),
  36 => 
  array (
    'symbol' => 'expressionC',
    'len' => 3,
    'replace' => true,
  ),
  37 => 
  array (
    'symbol' => 'expressionC',
    'len' => 3,
    'replace' => true,
  ),
  38 => 
  array (
    'symbol' => 'expressionC',
    'len' => 4,
    'replace' => true,
  ),
  39 => 
  array (
    'symbol' => 'expressionC',
    'len' => 4,
    'replace' => true,
  ),
  40 => 
  array (
    'symbol' => 'expressionC',
    'len' => 4,
    'replace' => true,
  ),
  41 => 
  array (
    'symbol' => 'expressionC',
    'len' => 1,
    'replace' => true,
  ),
  42 => 
  array (
    'symbol' => 'expressionD',
    'len' => 3,
    'replace' => true,
  ),
  43 => 
  array (
    'symbol' => 'expressionD',
    'len' => 3,
    'replace' => true,
  ),
  44 => 
  array (
    'symbol' => 'expressionD',
    'len' => 1,
    'replace' => true,
  ),
  45 => 
  array (
    'symbol' => 'expressionE',
    'len' => 3,
    'replace' => true,
  ),
  46 => 
  array (
    'symbol' => 'expressionE',
    'len' => 3,
    'replace' => true,
  ),
  47 => 
  array (
    'symbol' => 'expressionE',
    'len' => 1,
    'replace' => true,
  ),
  48 => 
  array (
    'symbol' => 'expressionF',
    'len' => 1,
    'replace' => true,
  ),
  49 => 
  array (
    'symbol' => 'endexpression',
    'len' => 1,
    'replace' => true,
  ),
  50 => 
  array (
    'symbol' => 'endexpression',
    'len' => 3,
    'replace' => true,
  ),
  51 => 
  array (
    'symbol' => 'endexpression',
    'len' => 1,
    'replace' => true,
  ),
  52 => 
  array (
    'symbol' => 'endexpression',
    'len' => 4,
    'replace' => true,
  ),
  53 => 
  array (
    'symbol' => 'endexpression',
    'len' => 6,
    'replace' => true,
  ),
  54 => 
  array (
    'symbol' => 'endexpression',
    'len' => 8,
    'replace' => true,
  ),
  55 => 
  array (
    'symbol' => 'likeexpression',
    'len' => 1,
    'replace' => true,
  ),
  56 => 
  array (
    'symbol' => 'identifierlist',
    'len' => 1,
    'replace' => true,
  ),
  57 => 
  array (
    'symbol' => 'identifierlist',
    'len' => 3,
    'replace' => true,
  ),
  58 => 
  array (
    'symbol' => 'allowedalias',
    'len' => 1,
    'replace' => true,
  ),
  59 => 
  array (
    'symbol' => 'identifier',
    'len' => 1,
    'replace' => true,
  ),
  60 => 
  array (
    'symbol' => 'identifier',
    'len' => 1,
    'replace' => true,
  ),
  61 => 
  array (
    'symbol' => '\'start\'',
    'len' => 1,
    'replace' => true,
  ),
);
}
