<?php


/*

DON'T EDIT THIS FILE!

This file was automatically generated by the Lime parser generator.
The real source code you should be looking at is in one or more
grammar files in the Lime format.

THE ONLY REASON TO LOOK AT THIS FILE is to see where in the grammar
file that your error happened, because there are enough comments to
help you debug your grammar.

If you ignore this warning, you're shooting yourself in the brain,
not the foot.

*/

class SQLgrammar extends lime_parser {
var $qi = 0;
var $i = array (
  0 => 
  array (
    'selectfromstatement' => 's 1',
    'unionstatement' => 's 2',
    'expression' => 's 3',
    'SELECT' => 's 86',
    'expressionA' => 's 6',
    'IN' => 's 79',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
    'filterresult' => 's 108',
    '\'start\'' => 'a \'start\'',
  ),
  1 => 
  array (
    '#' => 'r 0',
  ),
  2 => 
  array (
    '#' => 'r 1',
  ),
  3 => 
  array (
    'UNION' => 's 4',
  ),
  4 => 
  array (
    'expression' => 's 5',
    'expressionA' => 's 6',
    'IN' => 's 79',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  5 => 
  array (
    '#' => 'r 2',
  ),
  6 => 
  array (
    'BETWEEN' => 's 7',
    'INNER' => 's 56',
    'LEFT' => 's 61',
    'RIGHT' => 's 66',
    'FULL' => 's 71',
    'LIKE' => 's 76',
    'UNION' => 'r 18',
    '\',\'' => 'r 18',
    'FROM' => 'r 18',
    'WHERE' => 'r 18',
    'GROUP' => 'r 18',
    '#' => 'r 18',
  ),
  7 => 
  array (
    'expressionA' => 's 8',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  8 => 
  array (
    'AND' => 's 9',
  ),
  9 => 
  array (
    'expressionA' => 's 10',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  10 => 
  array (
    'UNION' => 'r 19',
    '\',\'' => 'r 19',
    'FROM' => 'r 19',
    'WHERE' => 'r 19',
    'GROUP' => 'r 19',
    '#' => 'r 19',
  ),
  11 => 
  array (
    'OR' => 's 12',
    'LIKE' => 'r 27',
    'FULL' => 'r 27',
    'RIGHT' => 'r 27',
    'LEFT' => 'r 27',
    'INNER' => 'r 27',
    'BETWEEN' => 'r 27',
    'UNION' => 'r 27',
    'AND' => 'r 27',
    'ON' => 'r 27',
    '\',\'' => 'r 27',
    'FROM' => 'r 27',
    'WHERE' => 'r 27',
    'GROUP' => 'r 27',
    '#' => 'r 27',
  ),
  12 => 
  array (
    'expressionB' => 's 11',
    'expressionA' => 's 13',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  13 => 
  array (
    'LIKE' => 'r 26',
    'FULL' => 'r 26',
    'RIGHT' => 'r 26',
    'LEFT' => 'r 26',
    'INNER' => 'r 26',
    'BETWEEN' => 'r 26',
    'UNION' => 'r 26',
    'AND' => 'r 26',
    'ON' => 'r 26',
    '\',\'' => 'r 26',
    'FROM' => 'r 26',
    'WHERE' => 'r 26',
    'GROUP' => 'r 26',
    '#' => 'r 26',
  ),
  14 => 
  array (
    'AND' => 's 15',
    'OR' => 'r 29',
    'LIKE' => 'r 29',
    'FULL' => 'r 29',
    'RIGHT' => 'r 29',
    'LEFT' => 'r 29',
    'INNER' => 'r 29',
    'BETWEEN' => 'r 29',
    'UNION' => 'r 29',
    'ON' => 'r 29',
    '\',\'' => 'r 29',
    'FROM' => 'r 29',
    'WHERE' => 'r 29',
    'GROUP' => 'r 29',
    '#' => 'r 29',
  ),
  15 => 
  array (
    'expressionC' => 's 14',
    'expressionB' => 's 16',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  16 => 
  array (
    'OR' => 'r 28',
    'LIKE' => 'r 28',
    'FULL' => 'r 28',
    'RIGHT' => 'r 28',
    'LEFT' => 'r 28',
    'INNER' => 'r 28',
    'BETWEEN' => 'r 28',
    'UNION' => 'r 28',
    'AND' => 'r 28',
    'ON' => 'r 28',
    '\',\'' => 'r 28',
    'FROM' => 'r 28',
    'WHERE' => 'r 28',
    'GROUP' => 'r 28',
    '#' => 'r 28',
  ),
  17 => 
  array (
    '\'=\'' => 's 18',
    '\'<\'' => 's 46',
    '\'>\'' => 's 52',
    'AND' => 'r 36',
    'OR' => 'r 36',
    'LIKE' => 'r 36',
    'FULL' => 'r 36',
    'RIGHT' => 'r 36',
    'LEFT' => 'r 36',
    'INNER' => 'r 36',
    'BETWEEN' => 'r 36',
    'UNION' => 'r 36',
    'ON' => 'r 36',
    '\',\'' => 'r 36',
    'FROM' => 'r 36',
    'WHERE' => 'r 36',
    'GROUP' => 'r 36',
    '#' => 'r 36',
  ),
  18 => 
  array (
    'expressionD' => 's 19',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  19 => 
  array (
    'AND' => 'r 30',
    'OR' => 'r 30',
    'LIKE' => 'r 30',
    'FULL' => 'r 30',
    'RIGHT' => 'r 30',
    'LEFT' => 'r 30',
    'INNER' => 'r 30',
    'BETWEEN' => 'r 30',
    'UNION' => 'r 30',
    'ON' => 'r 30',
    '\',\'' => 'r 30',
    'FROM' => 'r 30',
    'WHERE' => 'r 30',
    'GROUP' => 'r 30',
    '#' => 'r 30',
  ),
  20 => 
  array (
    '\'+\'' => 's 21',
    '\'-\'' => 's 44',
    '\'<\'' => 'r 39',
    '\'>\'' => 'r 39',
    '\'=\'' => 'r 39',
    'AND' => 'r 39',
    'OR' => 'r 39',
    'LIKE' => 'r 39',
    'FULL' => 'r 39',
    'RIGHT' => 'r 39',
    'LEFT' => 'r 39',
    'INNER' => 'r 39',
    'BETWEEN' => 'r 39',
    'UNION' => 'r 39',
    'ON' => 'r 39',
    '\',\'' => 'r 39',
    'FROM' => 'r 39',
    'WHERE' => 'r 39',
    'GROUP' => 'r 39',
    '#' => 'r 39',
  ),
  21 => 
  array (
    'expressionE' => 's 20',
    'expressionD' => 's 22',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  22 => 
  array (
    '\'<\'' => 'r 37',
    '\'>\'' => 'r 37',
    '\'=\'' => 'r 37',
    'AND' => 'r 37',
    'OR' => 'r 37',
    'LIKE' => 'r 37',
    'FULL' => 'r 37',
    'RIGHT' => 'r 37',
    'LEFT' => 'r 37',
    'INNER' => 'r 37',
    'BETWEEN' => 'r 37',
    'UNION' => 'r 37',
    'ON' => 'r 37',
    '\',\'' => 'r 37',
    'FROM' => 'r 37',
    'WHERE' => 'r 37',
    'GROUP' => 'r 37',
    '#' => 'r 37',
  ),
  23 => 
  array (
    '\'*\'' => 's 24',
    '\'/\'' => 's 42',
    '\'-\'' => 'r 42',
    '\'+\'' => 'r 42',
    '\'<\'' => 'r 42',
    '\'>\'' => 'r 42',
    '\'=\'' => 'r 42',
    'AND' => 'r 42',
    'OR' => 'r 42',
    'LIKE' => 'r 42',
    'FULL' => 'r 42',
    'RIGHT' => 'r 42',
    'LEFT' => 'r 42',
    'INNER' => 'r 42',
    'BETWEEN' => 'r 42',
    'UNION' => 'r 42',
    'ON' => 'r 42',
    '\',\'' => 'r 42',
    'FROM' => 'r 42',
    'WHERE' => 'r 42',
    'GROUP' => 'r 42',
    '#' => 'r 42',
  ),
  24 => 
  array (
    'expressionF' => 's 23',
    'expressionE' => 's 25',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  25 => 
  array (
    '\'-\'' => 'r 40',
    '\'+\'' => 'r 40',
    '\'<\'' => 'r 40',
    '\'>\'' => 'r 40',
    '\'=\'' => 'r 40',
    'AND' => 'r 40',
    'OR' => 'r 40',
    'LIKE' => 'r 40',
    'FULL' => 'r 40',
    'RIGHT' => 'r 40',
    'LEFT' => 'r 40',
    'INNER' => 'r 40',
    'BETWEEN' => 'r 40',
    'UNION' => 'r 40',
    'ON' => 'r 40',
    '\',\'' => 'r 40',
    'FROM' => 'r 40',
    'WHERE' => 'r 40',
    'GROUP' => 'r 40',
    '#' => 'r 40',
  ),
  26 => 
  array (
    '\'/\'' => 'r 43',
    '\'*\'' => 'r 43',
    '\'-\'' => 'r 43',
    '\'+\'' => 'r 43',
    '\'<\'' => 'r 43',
    '\'>\'' => 'r 43',
    '\'=\'' => 'r 43',
    'AND' => 'r 43',
    'OR' => 'r 43',
    'LIKE' => 'r 43',
    'FULL' => 'r 43',
    'RIGHT' => 'r 43',
    'LEFT' => 'r 43',
    'INNER' => 'r 43',
    'BETWEEN' => 'r 43',
    'UNION' => 'r 43',
    'ON' => 'r 43',
    '\',\'' => 'r 43',
    'FROM' => 'r 43',
    'WHERE' => 'r 43',
    'GROUP' => 'r 43',
    '#' => 'r 43',
  ),
  27 => 
  array (
    '\'(\'' => 's 28',
    '\'/\'' => 'r 44',
    '\'*\'' => 'r 44',
    '\'-\'' => 'r 44',
    '\'+\'' => 'r 44',
    '\'<\'' => 'r 44',
    '\'>\'' => 'r 44',
    '\'=\'' => 'r 44',
    'AND' => 'r 44',
    'OR' => 'r 44',
    'LIKE' => 'r 44',
    'FULL' => 'r 44',
    'RIGHT' => 'r 44',
    'LEFT' => 'r 44',
    'INNER' => 'r 44',
    'BETWEEN' => 'r 44',
    'UNION' => 'r 44',
    'ON' => 'r 44',
    '\',\'' => 'r 44',
    'FROM' => 'r 44',
    'WHERE' => 'r 44',
    'GROUP' => 'r 44',
    '#' => 'r 44',
  ),
  28 => 
  array (
    'statement' => 's 29',
  ),
  29 => 
  array (
    '\')\'' => 's 30',
    '\',\'' => 's 31',
  ),
  30 => 
  array (
    '\'/\'' => 'r 47',
    '\'*\'' => 'r 47',
    '\'-\'' => 'r 47',
    '\'+\'' => 'r 47',
    '\'<\'' => 'r 47',
    '\'>\'' => 'r 47',
    '\'=\'' => 'r 47',
    'AND' => 'r 47',
    'OR' => 'r 47',
    'LIKE' => 'r 47',
    'FULL' => 'r 47',
    'RIGHT' => 'r 47',
    'LEFT' => 'r 47',
    'INNER' => 'r 47',
    'BETWEEN' => 'r 47',
    'UNION' => 'r 47',
    'ON' => 'r 47',
    '\',\'' => 'r 47',
    'FROM' => 'r 47',
    'WHERE' => 'r 47',
    'GROUP' => 'r 47',
    '#' => 'r 47',
  ),
  31 => 
  array (
    'statement' => 's 32',
  ),
  32 => 
  array (
    '\')\'' => 's 33',
    '\',\'' => 's 34',
  ),
  33 => 
  array (
    '\'/\'' => 'r 48',
    '\'*\'' => 'r 48',
    '\'-\'' => 'r 48',
    '\'+\'' => 'r 48',
    '\'<\'' => 'r 48',
    '\'>\'' => 'r 48',
    '\'=\'' => 'r 48',
    'AND' => 'r 48',
    'OR' => 'r 48',
    'LIKE' => 'r 48',
    'FULL' => 'r 48',
    'RIGHT' => 'r 48',
    'LEFT' => 'r 48',
    'INNER' => 'r 48',
    'BETWEEN' => 'r 48',
    'UNION' => 'r 48',
    '\',\'' => 'r 48',
    'FROM' => 'r 48',
    'WHERE' => 'r 48',
    'GROUP' => 'r 48',
    'ON' => 'r 48',
    '#' => 'r 48',
  ),
  34 => 
  array (
    'statement' => 's 35',
  ),
  35 => 
  array (
    '\')\'' => 's 36',
  ),
  36 => 
  array (
    '\'/\'' => 'r 50',
    '\'*\'' => 'r 50',
    '\'-\'' => 'r 50',
    '\'+\'' => 'r 50',
    '\'<\'' => 'r 50',
    '\'>\'' => 'r 50',
    '\'=\'' => 'r 50',
    'AND' => 'r 50',
    'OR' => 'r 50',
    'LIKE' => 'r 50',
    'FULL' => 'r 50',
    'RIGHT' => 'r 50',
    'LEFT' => 'r 50',
    'INNER' => 'r 50',
    'BETWEEN' => 'r 50',
    'UNION' => 'r 50',
    'ON' => 'r 50',
    '\',\'' => 'r 50',
    'FROM' => 'r 50',
    'WHERE' => 'r 50',
    'GROUP' => 'r 50',
    '#' => 'r 50',
  ),
  37 => 
  array (
    'statement' => 's 38',
  ),
  38 => 
  array (
    '\')\'' => 's 39',
  ),
  39 => 
  array (
    '\'/\'' => 'r 45',
    '\'*\'' => 'r 45',
    '\'-\'' => 'r 45',
    '\'+\'' => 'r 45',
    '\'<\'' => 'r 45',
    '\'>\'' => 'r 45',
    '\'=\'' => 'r 45',
    'AND' => 'r 45',
    'OR' => 'r 45',
    'LIKE' => 'r 45',
    'FULL' => 'r 45',
    'RIGHT' => 'r 45',
    'LEFT' => 'r 45',
    'INNER' => 'r 45',
    'BETWEEN' => 'r 45',
    'UNION' => 'r 45',
    'ON' => 'r 45',
    '\',\'' => 'r 45',
    'FROM' => 'r 45',
    'WHERE' => 'r 45',
    'GROUP' => 'r 45',
    '#' => 'r 45',
  ),
  40 => 
  array (
    '\'/\'' => 'r 46',
    '\'*\'' => 'r 46',
    '\'-\'' => 'r 46',
    '\'+\'' => 'r 46',
    '\'<\'' => 'r 46',
    '\'>\'' => 'r 46',
    '\'=\'' => 'r 46',
    'AND' => 'r 46',
    'OR' => 'r 46',
    'LIKE' => 'r 46',
    'FULL' => 'r 46',
    'RIGHT' => 'r 46',
    'LEFT' => 'r 46',
    'INNER' => 'r 46',
    'BETWEEN' => 'r 46',
    'UNION' => 'r 46',
    'ON' => 'r 46',
    '\',\'' => 'r 46',
    'FROM' => 'r 46',
    'WHERE' => 'r 46',
    'GROUP' => 'r 46',
    '#' => 'r 46',
  ),
  41 => 
  array (
    '\'/\'' => 'r 49',
    '\'*\'' => 'r 49',
    '\'-\'' => 'r 49',
    '\'+\'' => 'r 49',
    '\'<\'' => 'r 49',
    '\'>\'' => 'r 49',
    '\'=\'' => 'r 49',
    'AND' => 'r 49',
    'OR' => 'r 49',
    'LIKE' => 'r 49',
    'FULL' => 'r 49',
    'RIGHT' => 'r 49',
    'LEFT' => 'r 49',
    'INNER' => 'r 49',
    'BETWEEN' => 'r 49',
    'UNION' => 'r 49',
    'ON' => 'r 49',
    '\',\'' => 'r 49',
    'FROM' => 'r 49',
    'WHERE' => 'r 49',
    'GROUP' => 'r 49',
    '#' => 'r 49',
  ),
  42 => 
  array (
    'expressionF' => 's 23',
    'expressionE' => 's 43',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  43 => 
  array (
    '\'-\'' => 'r 41',
    '\'+\'' => 'r 41',
    '\'<\'' => 'r 41',
    '\'>\'' => 'r 41',
    '\'=\'' => 'r 41',
    'AND' => 'r 41',
    'OR' => 'r 41',
    'LIKE' => 'r 41',
    'FULL' => 'r 41',
    'RIGHT' => 'r 41',
    'LEFT' => 'r 41',
    'INNER' => 'r 41',
    'BETWEEN' => 'r 41',
    'UNION' => 'r 41',
    'ON' => 'r 41',
    '\',\'' => 'r 41',
    'FROM' => 'r 41',
    'WHERE' => 'r 41',
    'GROUP' => 'r 41',
    '#' => 'r 41',
  ),
  44 => 
  array (
    'expressionE' => 's 20',
    'expressionD' => 's 45',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  45 => 
  array (
    '\'<\'' => 'r 38',
    '\'>\'' => 'r 38',
    '\'=\'' => 'r 38',
    'AND' => 'r 38',
    'OR' => 'r 38',
    'LIKE' => 'r 38',
    'FULL' => 'r 38',
    'RIGHT' => 'r 38',
    'LEFT' => 'r 38',
    'INNER' => 'r 38',
    'BETWEEN' => 'r 38',
    'UNION' => 'r 38',
    'ON' => 'r 38',
    '\',\'' => 'r 38',
    'FROM' => 'r 38',
    'WHERE' => 'r 38',
    'GROUP' => 'r 38',
    '#' => 'r 38',
  ),
  46 => 
  array (
    'expressionD' => 's 47',
    '\'=\'' => 's 48',
    '\'>\'' => 's 50',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  47 => 
  array (
    'AND' => 'r 31',
    'OR' => 'r 31',
    'LIKE' => 'r 31',
    'FULL' => 'r 31',
    'RIGHT' => 'r 31',
    'LEFT' => 'r 31',
    'INNER' => 'r 31',
    'BETWEEN' => 'r 31',
    'UNION' => 'r 31',
    'ON' => 'r 31',
    '\',\'' => 'r 31',
    'FROM' => 'r 31',
    'WHERE' => 'r 31',
    'GROUP' => 'r 31',
    '#' => 'r 31',
  ),
  48 => 
  array (
    'expressionD' => 's 49',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  49 => 
  array (
    'AND' => 'r 33',
    'OR' => 'r 33',
    'LIKE' => 'r 33',
    'FULL' => 'r 33',
    'RIGHT' => 'r 33',
    'LEFT' => 'r 33',
    'INNER' => 'r 33',
    'BETWEEN' => 'r 33',
    'UNION' => 'r 33',
    'ON' => 'r 33',
    '\',\'' => 'r 33',
    'FROM' => 'r 33',
    'WHERE' => 'r 33',
    'GROUP' => 'r 33',
    '#' => 'r 33',
  ),
  50 => 
  array (
    'expressionD' => 's 51',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  51 => 
  array (
    'AND' => 'r 35',
    'OR' => 'r 35',
    'LIKE' => 'r 35',
    'FULL' => 'r 35',
    'RIGHT' => 'r 35',
    'LEFT' => 'r 35',
    'INNER' => 'r 35',
    'BETWEEN' => 'r 35',
    'UNION' => 'r 35',
    'ON' => 'r 35',
    '\',\'' => 'r 35',
    'FROM' => 'r 35',
    'WHERE' => 'r 35',
    'GROUP' => 'r 35',
    '#' => 'r 35',
  ),
  52 => 
  array (
    'expressionD' => 's 53',
    '\'=\'' => 's 54',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  53 => 
  array (
    'AND' => 'r 32',
    'OR' => 'r 32',
    'LIKE' => 'r 32',
    'FULL' => 'r 32',
    'RIGHT' => 'r 32',
    'LEFT' => 'r 32',
    'INNER' => 'r 32',
    'BETWEEN' => 'r 32',
    'UNION' => 'r 32',
    'ON' => 'r 32',
    '\',\'' => 'r 32',
    'FROM' => 'r 32',
    'WHERE' => 'r 32',
    'GROUP' => 'r 32',
    '#' => 'r 32',
  ),
  54 => 
  array (
    'expressionD' => 's 55',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  55 => 
  array (
    'AND' => 'r 34',
    'OR' => 'r 34',
    'LIKE' => 'r 34',
    'FULL' => 'r 34',
    'RIGHT' => 'r 34',
    'LEFT' => 'r 34',
    'INNER' => 'r 34',
    'BETWEEN' => 'r 34',
    'UNION' => 'r 34',
    'ON' => 'r 34',
    '\',\'' => 'r 34',
    'FROM' => 'r 34',
    'WHERE' => 'r 34',
    'GROUP' => 'r 34',
    '#' => 'r 34',
  ),
  56 => 
  array (
    'JOIN' => 's 57',
  ),
  57 => 
  array (
    'expressionA' => 's 58',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  58 => 
  array (
    'ON' => 's 59',
  ),
  59 => 
  array (
    'expressionA' => 's 60',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  60 => 
  array (
    'UNION' => 'r 21',
    '\',\'' => 'r 21',
    'FROM' => 'r 21',
    'WHERE' => 'r 21',
    'GROUP' => 'r 21',
    '#' => 'r 21',
  ),
  61 => 
  array (
    'JOIN' => 's 62',
  ),
  62 => 
  array (
    'expressionA' => 's 63',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  63 => 
  array (
    'ON' => 's 64',
  ),
  64 => 
  array (
    'expressionA' => 's 65',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  65 => 
  array (
    'UNION' => 'r 22',
    '\',\'' => 'r 22',
    'FROM' => 'r 22',
    'WHERE' => 'r 22',
    'GROUP' => 'r 22',
    '#' => 'r 22',
  ),
  66 => 
  array (
    'JOIN' => 's 67',
  ),
  67 => 
  array (
    'expressionA' => 's 68',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  68 => 
  array (
    'ON' => 's 69',
  ),
  69 => 
  array (
    'expressionA' => 's 70',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  70 => 
  array (
    'UNION' => 'r 23',
    '\',\'' => 'r 23',
    'FROM' => 'r 23',
    'WHERE' => 'r 23',
    'GROUP' => 'r 23',
    '#' => 'r 23',
  ),
  71 => 
  array (
    'JOIN' => 's 72',
  ),
  72 => 
  array (
    'expressionA' => 's 73',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  73 => 
  array (
    'ON' => 's 74',
  ),
  74 => 
  array (
    'expressionA' => 's 75',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  75 => 
  array (
    'UNION' => 'r 24',
    '\',\'' => 'r 24',
    'FROM' => 'r 24',
    'WHERE' => 'r 24',
    'GROUP' => 'r 24',
    '#' => 'r 24',
  ),
  76 => 
  array (
    'likeexpression' => 's 77',
    'constant' => 's 78',
  ),
  77 => 
  array (
    'UNION' => 'r 25',
    '\',\'' => 'r 25',
    'FROM' => 'r 25',
    'WHERE' => 'r 25',
    'GROUP' => 'r 25',
    '#' => 'r 25',
  ),
  78 => 
  array (
    'UNION' => 'r 51',
    '\',\'' => 'r 51',
    'FROM' => 'r 51',
    'WHERE' => 'r 51',
    'GROUP' => 'r 51',
    '#' => 'r 51',
  ),
  79 => 
  array (
    '\'(\'' => 's 80',
  ),
  80 => 
  array (
    'constant' => 's 81',
    'constantlist' => 's 84',
  ),
  81 => 
  array (
    '\',\'' => 's 82',
    '\')\'' => 'r 16',
  ),
  82 => 
  array (
    'constant' => 's 81',
    'constantlist' => 's 83',
  ),
  83 => 
  array (
    '\')\'' => 'r 17',
  ),
  84 => 
  array (
    '\')\'' => 's 85',
  ),
  85 => 
  array (
    'UNION' => 'r 20',
    '\',\'' => 'r 20',
    'FROM' => 'r 20',
    'WHERE' => 'r 20',
    'GROUP' => 'r 20',
    '#' => 'r 20',
  ),
  86 => 
  array (
    'uniquefilter' => 's 87',
    'DISTINCT' => 's 107',
    '\'*\'' => 'r 5',
    'IN' => 'r 5',
    'identifier' => 'r 5',
    '\'(\'' => 'r 5',
    'constant' => 'r 5',
  ),
  87 => 
  array (
    'tablelist' => 's 88',
    '\'*\'' => 's 102',
    'listoftables' => 's 103',
    'expression' => 's 104',
    'expressionA' => 's 6',
    'IN' => 's 79',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  88 => 
  array (
    'FROM' => 's 89',
  ),
  89 => 
  array (
    'expression' => 's 90',
    'expressionA' => 's 6',
    'IN' => 's 79',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  90 => 
  array (
    'wherefilter' => 's 91',
    'WHERE' => 's 100',
    'GROUP' => 'r 7',
    '#' => 'r 7',
  ),
  91 => 
  array (
    'groupfilter' => 's 92',
    'GROUP' => 's 93',
    '#' => 'r 9',
  ),
  92 => 
  array (
    '#' => 'r 3',
  ),
  93 => 
  array (
    'BY' => 's 94',
  ),
  94 => 
  array (
    'identifierlist' => 's 95',
    'identifier' => 's 97',
  ),
  95 => 
  array (
    'havingfiler' => 's 96',
  ),
  96 => 
  array (
    '#' => 'r 8',
  ),
  97 => 
  array (
    '\',\'' => 's 98',
    'havingfiler' => 'r 52',
  ),
  98 => 
  array (
    'identifier' => 's 97',
    'identifierlist' => 's 99',
  ),
  99 => 
  array (
    'havingfiler' => 'r 53',
  ),
  100 => 
  array (
    'expression' => 's 101',
    'expressionA' => 's 6',
    'IN' => 's 79',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  101 => 
  array (
    'GROUP' => 'r 6',
    '#' => 'r 6',
  ),
  102 => 
  array (
    'FROM' => 'r 12',
  ),
  103 => 
  array (
    'FROM' => 'r 13',
  ),
  104 => 
  array (
    '\',\'' => 's 105',
    'FROM' => 'r 14',
  ),
  105 => 
  array (
    '\'*\'' => 's 102',
    'listoftables' => 's 103',
    'expression' => 's 104',
    'tablelist' => 's 106',
    'expressionA' => 's 6',
    'IN' => 's 79',
    'expressionB' => 's 11',
    'expressionC' => 's 14',
    'expressionD' => 's 17',
    'expressionE' => 's 20',
    'expressionF' => 's 23',
    'endexpression' => 's 26',
    'identifier' => 's 27',
    '\'(\'' => 's 37',
    'constant' => 's 40',
    '\'endexpression\'48' => 's 41',
  ),
  106 => 
  array (
    'FROM' => 'r 15',
  ),
  107 => 
  array (
    '\'*\'' => 'r 4',
    'IN' => 'r 4',
    'identifier' => 'r 4',
    '\'(\'' => 'r 4',
    'constant' => 'r 4',
  ),
  108 => 
  array (
    '#' => 'r 54',
  ),
);
function reduce_0_filterresult_1($tokens, &$result) {
#
# (0) filterresult :=  selectfromstatement
#
$result = reset($tokens);
$result = $tokens[0];/*TODO*/
}

function reduce_1_filterresult_2($tokens, &$result) {
#
# (1) filterresult :=  unionstatement
#
$result = reset($tokens);
$result = $tokens[0];/*TODO*/
}

function reduce_2_unionstatement_1($tokens, &$result) {
#
# (2) unionstatement :=  expression  UNION  expression
#
$result = reset($tokens);
$expr1 =& $tokens[0];
$expr2 =& $tokens[2];
$result = null;/*TODO*/
}

function reduce_3_selectfromstatement_1($tokens, &$result) {
#
# (3) selectfromstatement :=  SELECT  uniquefilter  tablelist  FROM  expression  wherefilter  groupfilter
#
$result = reset($tokens);
$distinct =& $tokens[1];
$selecttables =& $tokens[2];
$fromtable =& $tokens[4];
$where =& $tokens[5];
$groupby =& $tokens[6];
// 1) fromtables
                         // 2) wherefilter (if defined)
                         // 3) groupbyfilter (if defined)
                         // 4) selecttables
                         // 5) distinctfilter (if defined)
                        
                        $totalfilter=$fromtable;
                        $totalfilter=putFilterAfterIfExists($totalfilter, $where);
                        $totalfilter=putFilterAfterIfExists($totalfilter, $groupby);
                        $totalfilter=putFilterAfterIfExists($totalfilter, new ColumnSelectionFilter($selecttables));
                        $totalfilter=putFilterAfterIfExists($totalfilter, $distinct);
                        
                        $result=$totalfilter;
}

function reduce_4_uniquefilter_1($tokens, &$result) {
#
# (4) uniquefilter :=  DISTINCT
#
$result = reset($tokens);
$result = new DistinctFilter();
}

function reduce_5_uniquefilter_2($tokens, &$result) {
#
# (5) uniquefilter :=
#
$result = reset($tokens);
$result = null;
}

function reduce_6_wherefilter_1($tokens, &$result) {
#
# (6) wherefilter :=  WHERE  expression
#
$result = reset($tokens);
$expr =& $tokens[1];
$result = new FilterByExpression($expr);
}

function reduce_7_wherefilter_2($tokens, &$result) {
#
# (7) wherefilter :=
#
$result = reset($tokens);
$result = null;
}

function reduce_8_groupfilter_1($tokens, &$result) {
#
# (8) groupfilter :=  GROUP  BY  identifierlist  havingfiler
#
$result = reset($tokens);
$groupFields =& $tokens[2];
$having =& $tokens[3];
$result = putFilterAfterIfExists(new DataGrouper($groupFields), $having);
}

function reduce_9_groupfilter_2($tokens, &$result) {
#
# (9) groupfilter :=
#
$result = reset($tokens);
$result = null;
}

function reduce_10_havingfilter_1($tokens, &$result) {
#
# (10) havingfilter :=  HAVING  expression
#
$result = reset($tokens);
$expr =& $tokens[1];
$result = new FilterByExpression($expr);
}

function reduce_11_havingfilter_2($tokens, &$result) {
#
# (11) havingfilter :=
#
$result = reset($tokens);
$result = null;
}

function reduce_12_tablelist_1($tokens, &$result) {
#
# (12) tablelist :=  '*'
#
$result = reset($tokens);
$result = array(ColumnSelectionFilter::$KEY_ALL);
}

function reduce_13_tablelist_2($tokens, &$result) {
#
# (13) tablelist :=  listoftables
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_14_listoftables_1($tokens, &$result) {
#
# (14) listoftables :=  expression
#
$result = reset($tokens);
$expr =& $tokens[0];
$result = array($expr);
}

function reduce_15_listoftables_2($tokens, &$result) {
#
# (15) listoftables :=  expression  ','  tablelist
#
$result = reset($tokens);
$expr =& $tokens[0];
$arr =& $tokens[2];
array_unshift($arr, $expr);$result = $arr;
}

function reduce_16_constantlist_1($tokens, &$result) {
#
# (16) constantlist :=  constant
#
$result = reset($tokens);
$result = array(new Constant($tokens[0]));
}

function reduce_17_constantlist_2($tokens, &$result) {
#
# (17) constantlist :=  constant  ','  constantlist
#
$result = reset($tokens);
$arr =& $tokens[2];
array_unshift($arr, $tokens[0]);$result = $arr;
}

function reduce_18_expression_1($tokens, &$result) {
#
# (18) expression :=  expressionA
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_19_expression_2($tokens, &$result) {
#
# (19) expression :=  expressionA  BETWEEN  expressionA  AND  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$c =& $tokens[4];
$result = new TertairyFunction(TertairyFunction::$FUNCTION_TERTIARY_BETWEEN, $a, $b, $c);
}

function reduce_20_expression_3($tokens, &$result) {
#
# (20) expression :=  IN  '('  constantlist  ')'
#
$result = reset($tokens);
$constantlist =& $tokens[2];
$result = new CheckInFunction($constantlist);
}

function reduce_21_expression_4($tokens, &$result) {
#
# (21) expression :=  expressionA  INNER  JOIN  expressionA  ON  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$c =& $tokens[5];
$result = null;/*TODO*/
}

function reduce_22_expression_5($tokens, &$result) {
#
# (22) expression :=  expressionA  LEFT  JOIN  expressionA  ON  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$c =& $tokens[5];
$result = null;/*TODO*/
}

function reduce_23_expression_6($tokens, &$result) {
#
# (23) expression :=  expressionA  RIGHT  JOIN  expressionA  ON  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$c =& $tokens[5];
$result = null;/*TODO*/
}

function reduce_24_expression_7($tokens, &$result) {
#
# (24) expression :=  expressionA  FULL  JOIN  expressionA  ON  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$c =& $tokens[5];
$result = null;/*TODO*/
}

function reduce_25_expression_8($tokens, &$result) {
#
# (25) expression :=  expressionA  LIKE  likeexpression
#
$result = reset($tokens);
$expr =& $tokens[0];
$likeexpr =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_UNAIRY_MATCH_REGEX, $expr, convertRegexFromSQLToUniversal($likeexpr));
}

function reduce_26_expressionA_1($tokens, &$result) {
#
# (26) expressionA :=  expressionB  OR  expressionA
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_OR, $a, $b);
}

function reduce_27_expressionA_2($tokens, &$result) {
#
# (27) expressionA :=  expressionB
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_28_expressionB_1($tokens, &$result) {
#
# (28) expressionB :=  expressionC  AND  expressionB
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_AND, $a, $b);
}

function reduce_29_expressionB_2($tokens, &$result) {
#
# (29) expressionB :=  expressionC
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_30_expressionC_1($tokens, &$result) {
#
# (30) expressionC :=  expressionD  '='  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_EQUAL, $a, $b);
}

function reduce_31_expressionC_2($tokens, &$result) {
#
# (31) expressionC :=  expressionD  '<'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_THAN, $a, $b);
}

function reduce_32_expressionC_3($tokens, &$result) {
#
# (32) expressionC :=  expressionD  '>'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_LARGER_THAN, $a, $b);
}

function reduce_33_expressionC_4($tokens, &$result) {
#
# (33) expressionC :=  expressionD  '<'  '='  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_SMALLER_OR_EQUAL_THAN, $a, $b);
}

function reduce_34_expressionC_5($tokens, &$result) {
#
# (34) expressionC :=  expressionD  '>'  '='  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_LARGER_OR_EQUAL_THAN, $a, $b);
}

function reduce_35_expressionC_6($tokens, &$result) {
#
# (35) expressionC :=  expressionD  '<'  '>'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[3];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_COMPARE_NOTEQUAL, $a, $b);
}

function reduce_36_expressionC_7($tokens, &$result) {
#
# (36) expressionC :=  expressionD
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_37_expressionD_1($tokens, &$result) {
#
# (37) expressionD :=  expressionE  '+'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_PLUS, $a, $b);
}

function reduce_38_expressionD_2($tokens, &$result) {
#
# (38) expressionD :=  expressionE  '-'  expressionD
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_MINUS, $a, $b);
}

function reduce_39_expressionD_3($tokens, &$result) {
#
# (39) expressionD :=  expressionE
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_40_expressionE_1($tokens, &$result) {
#
# (40) expressionE :=  expressionF  '*'  expressionE
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_MULTIPLY, $a, $b);
}

function reduce_41_expressionE_2($tokens, &$result) {
#
# (41) expressionE :=  expressionF  '/'  expressionE
#
$result = reset($tokens);
$a =& $tokens[0];
$b =& $tokens[2];
$result = new BinaryFunction(BinaryFunction::$FUNCTION_BINARY_DIVIDE, $a, $b);
}

function reduce_42_expressionE_3($tokens, &$result) {
#
# (42) expressionE :=  expressionF
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_43_expressionF_1($tokens, &$result) {
#
# (43) expressionF :=  endexpression
#
$result = reset($tokens);
$result = $tokens[0];
}

function reduce_44_endexpression_1($tokens, &$result) {
#
# (44) endexpression :=  identifier
#
$result = reset($tokens);
$result = new Identifier($tokens[0]);
}

function reduce_45_endexpression_2($tokens, &$result) {
#
# (45) endexpression :=  '('  statement  ')'
#
$result = reset($tokens);
$stat =& $tokens[1];
$result = $stat;
}

function reduce_46_endexpression_3($tokens, &$result) {
#
# (46) endexpression :=  constant
#
$result = reset($tokens);
$result = new Constant($tokens[0]);
}

function reduce_47_endexpression_4($tokens, &$result) {
#
# (47) endexpression :=  identifier  '('  statement  ')'
#
$result = reset($tokens);
$functid =& $tokens[0];
$arg1 =& $tokens[2];
$result = getUnaryFilterForSQLFunction($functid, $arg1);
}

function reduce_48_endexpression48_1($tokens, &$result) {
#
# (48) 'endexpression'48 :=  identifier  '('  statement  ','  statement  ')'
#
$result = reset($tokens);
$functid =& $tokens[0];
$arg1 =& $tokens[2];
$arg2 =& $tokens[4];
$result = null;
}

function reduce_49_endexpression_5($tokens, &$result) {
#
# (49) endexpression :=  'endexpression'48
#
$result = reset($tokens);
$functid =& $tokens[0];
$arg1 =& $tokens[2];
$arg2 =& $tokens[4];
$result = getBinaryFunctionForSQLFunction($functid, $arg1, $arg2);
}

function reduce_50_endexpression_6($tokens, &$result) {
#
# (50) endexpression :=  identifier  '('  statement  ','  statement  ','  statement  ')'
#
$result = reset($tokens);
$functid =& $tokens[0];
$arg1 =& $tokens[2];
$arg2 =& $tokens[4];
$arg3 =& $tokens[6];
$result =getTertairyFunctionForSQLFunction($functid, $arg1, $arg2, $arg3);
}

function reduce_51_likeexpression_1($tokens, &$result) {
#
# (51) likeexpression :=  constant
#
$result = reset($tokens);
$result = new Constant($tokens[0]);
}

function reduce_52_identifierlist_1($tokens, &$result) {
#
# (52) identifierlist :=  identifier
#
$result = reset($tokens);
$result = array(new Identifier($tokens[0]));
}

function reduce_53_identifierlist_2($tokens, &$result) {
#
# (53) identifierlist :=  identifier  ','  identifierlist
#
$result = reset($tokens);
$arr =& $tokens[2];
$result = array_unshift($arr, $tokens[0]);
}

function reduce_54_start_1($tokens, &$result) {
#
# (54) 'start' :=  filterresult
#
$result = reset($tokens);

}

var $method = array (
  0 => 'reduce_0_filterresult_1',
  1 => 'reduce_1_filterresult_2',
  2 => 'reduce_2_unionstatement_1',
  3 => 'reduce_3_selectfromstatement_1',
  4 => 'reduce_4_uniquefilter_1',
  5 => 'reduce_5_uniquefilter_2',
  6 => 'reduce_6_wherefilter_1',
  7 => 'reduce_7_wherefilter_2',
  8 => 'reduce_8_groupfilter_1',
  9 => 'reduce_9_groupfilter_2',
  10 => 'reduce_10_havingfilter_1',
  11 => 'reduce_11_havingfilter_2',
  12 => 'reduce_12_tablelist_1',
  13 => 'reduce_13_tablelist_2',
  14 => 'reduce_14_listoftables_1',
  15 => 'reduce_15_listoftables_2',
  16 => 'reduce_16_constantlist_1',
  17 => 'reduce_17_constantlist_2',
  18 => 'reduce_18_expression_1',
  19 => 'reduce_19_expression_2',
  20 => 'reduce_20_expression_3',
  21 => 'reduce_21_expression_4',
  22 => 'reduce_22_expression_5',
  23 => 'reduce_23_expression_6',
  24 => 'reduce_24_expression_7',
  25 => 'reduce_25_expression_8',
  26 => 'reduce_26_expressionA_1',
  27 => 'reduce_27_expressionA_2',
  28 => 'reduce_28_expressionB_1',
  29 => 'reduce_29_expressionB_2',
  30 => 'reduce_30_expressionC_1',
  31 => 'reduce_31_expressionC_2',
  32 => 'reduce_32_expressionC_3',
  33 => 'reduce_33_expressionC_4',
  34 => 'reduce_34_expressionC_5',
  35 => 'reduce_35_expressionC_6',
  36 => 'reduce_36_expressionC_7',
  37 => 'reduce_37_expressionD_1',
  38 => 'reduce_38_expressionD_2',
  39 => 'reduce_39_expressionD_3',
  40 => 'reduce_40_expressionE_1',
  41 => 'reduce_41_expressionE_2',
  42 => 'reduce_42_expressionE_3',
  43 => 'reduce_43_expressionF_1',
  44 => 'reduce_44_endexpression_1',
  45 => 'reduce_45_endexpression_2',
  46 => 'reduce_46_endexpression_3',
  47 => 'reduce_47_endexpression_4',
  48 => 'reduce_48_endexpression48_1',
  49 => 'reduce_49_endexpression_5',
  50 => 'reduce_50_endexpression_6',
  51 => 'reduce_51_likeexpression_1',
  52 => 'reduce_52_identifierlist_1',
  53 => 'reduce_53_identifierlist_2',
  54 => 'reduce_54_start_1',
);
var $a = array (
  0 => 
  array (
    'symbol' => 'filterresult',
    'len' => 1,
    'replace' => true,
  ),
  1 => 
  array (
    'symbol' => 'filterresult',
    'len' => 1,
    'replace' => true,
  ),
  2 => 
  array (
    'symbol' => 'unionstatement',
    'len' => 3,
    'replace' => true,
  ),
  3 => 
  array (
    'symbol' => 'selectfromstatement',
    'len' => 7,
    'replace' => true,
  ),
  4 => 
  array (
    'symbol' => 'uniquefilter',
    'len' => 1,
    'replace' => true,
  ),
  5 => 
  array (
    'symbol' => 'uniquefilter',
    'len' => 0,
    'replace' => true,
  ),
  6 => 
  array (
    'symbol' => 'wherefilter',
    'len' => 2,
    'replace' => true,
  ),
  7 => 
  array (
    'symbol' => 'wherefilter',
    'len' => 0,
    'replace' => true,
  ),
  8 => 
  array (
    'symbol' => 'groupfilter',
    'len' => 4,
    'replace' => true,
  ),
  9 => 
  array (
    'symbol' => 'groupfilter',
    'len' => 0,
    'replace' => true,
  ),
  10 => 
  array (
    'symbol' => 'havingfilter',
    'len' => 2,
    'replace' => true,
  ),
  11 => 
  array (
    'symbol' => 'havingfilter',
    'len' => 0,
    'replace' => true,
  ),
  12 => 
  array (
    'symbol' => 'tablelist',
    'len' => 1,
    'replace' => true,
  ),
  13 => 
  array (
    'symbol' => 'tablelist',
    'len' => 1,
    'replace' => true,
  ),
  14 => 
  array (
    'symbol' => 'listoftables',
    'len' => 1,
    'replace' => true,
  ),
  15 => 
  array (
    'symbol' => 'listoftables',
    'len' => 3,
    'replace' => true,
  ),
  16 => 
  array (
    'symbol' => 'constantlist',
    'len' => 1,
    'replace' => true,
  ),
  17 => 
  array (
    'symbol' => 'constantlist',
    'len' => 3,
    'replace' => true,
  ),
  18 => 
  array (
    'symbol' => 'expression',
    'len' => 1,
    'replace' => true,
  ),
  19 => 
  array (
    'symbol' => 'expression',
    'len' => 5,
    'replace' => true,
  ),
  20 => 
  array (
    'symbol' => 'expression',
    'len' => 4,
    'replace' => true,
  ),
  21 => 
  array (
    'symbol' => 'expression',
    'len' => 6,
    'replace' => true,
  ),
  22 => 
  array (
    'symbol' => 'expression',
    'len' => 6,
    'replace' => true,
  ),
  23 => 
  array (
    'symbol' => 'expression',
    'len' => 6,
    'replace' => true,
  ),
  24 => 
  array (
    'symbol' => 'expression',
    'len' => 6,
    'replace' => true,
  ),
  25 => 
  array (
    'symbol' => 'expression',
    'len' => 3,
    'replace' => true,
  ),
  26 => 
  array (
    'symbol' => 'expressionA',
    'len' => 3,
    'replace' => true,
  ),
  27 => 
  array (
    'symbol' => 'expressionA',
    'len' => 1,
    'replace' => true,
  ),
  28 => 
  array (
    'symbol' => 'expressionB',
    'len' => 3,
    'replace' => true,
  ),
  29 => 
  array (
    'symbol' => 'expressionB',
    'len' => 1,
    'replace' => true,
  ),
  30 => 
  array (
    'symbol' => 'expressionC',
    'len' => 3,
    'replace' => true,
  ),
  31 => 
  array (
    'symbol' => 'expressionC',
    'len' => 3,
    'replace' => true,
  ),
  32 => 
  array (
    'symbol' => 'expressionC',
    'len' => 3,
    'replace' => true,
  ),
  33 => 
  array (
    'symbol' => 'expressionC',
    'len' => 4,
    'replace' => true,
  ),
  34 => 
  array (
    'symbol' => 'expressionC',
    'len' => 4,
    'replace' => true,
  ),
  35 => 
  array (
    'symbol' => 'expressionC',
    'len' => 4,
    'replace' => true,
  ),
  36 => 
  array (
    'symbol' => 'expressionC',
    'len' => 1,
    'replace' => true,
  ),
  37 => 
  array (
    'symbol' => 'expressionD',
    'len' => 3,
    'replace' => true,
  ),
  38 => 
  array (
    'symbol' => 'expressionD',
    'len' => 3,
    'replace' => true,
  ),
  39 => 
  array (
    'symbol' => 'expressionD',
    'len' => 1,
    'replace' => true,
  ),
  40 => 
  array (
    'symbol' => 'expressionE',
    'len' => 3,
    'replace' => true,
  ),
  41 => 
  array (
    'symbol' => 'expressionE',
    'len' => 3,
    'replace' => true,
  ),
  42 => 
  array (
    'symbol' => 'expressionE',
    'len' => 1,
    'replace' => true,
  ),
  43 => 
  array (
    'symbol' => 'expressionF',
    'len' => 1,
    'replace' => true,
  ),
  44 => 
  array (
    'symbol' => 'endexpression',
    'len' => 1,
    'replace' => true,
  ),
  45 => 
  array (
    'symbol' => 'endexpression',
    'len' => 3,
    'replace' => true,
  ),
  46 => 
  array (
    'symbol' => 'endexpression',
    'len' => 1,
    'replace' => true,
  ),
  47 => 
  array (
    'symbol' => 'endexpression',
    'len' => 4,
    'replace' => true,
  ),
  48 => 
  array (
    'symbol' => '\'endexpression\'48',
    'len' => 6,
    'replace' => false,
  ),
  49 => 
  array (
    'symbol' => 'endexpression',
    'len' => 7,
    'replace' => true,
  ),
  50 => 
  array (
    'symbol' => 'endexpression',
    'len' => 8,
    'replace' => true,
  ),
  51 => 
  array (
    'symbol' => 'likeexpression',
    'len' => 1,
    'replace' => true,
  ),
  52 => 
  array (
    'symbol' => 'identifierlist',
    'len' => 1,
    'replace' => true,
  ),
  53 => 
  array (
    'symbol' => 'identifierlist',
    'len' => 3,
    'replace' => true,
  ),
  54 => 
  array (
    'symbol' => '\'start\'',
    'len' => 1,
    'replace' => true,
  ),
);
}
