<?php
/**
 * This file prettyprints autogenerated API Documentation.
 * of specific methods of a module.
 * @package The-Datatank/docs
 * @copyright (C) 2011 by iRail vzw/asbl
 * @license AGPLv3
 * @author Pieter Colpaert   <pieter@iRail.be>
 * @author Jan Vansteenlandt <jan@iRail.be>
 */
class DocPage {

    function GET($matches) {

	$module = $matches[1];
	$resource = $matches[2];

	/*
	 * There are two possibilities: the module/resource is a local one OR the module/resource is a remote one
	 * We'll have to check our proxymodules in order to know which one it is.
	 *
	 * If it's a remote one we need to get the documentation through a documentation module which is
	 * called TDTInfo, the resource Module expects the mod="modulename" and meth="resourcename" and returns it's
	 * documentation.
	 */
	$resourcename = $resource;

	$url = Config::$HOSTNAME .Config::$SUBDIR. "TDTInfo/Modules/$module/$resource/?format=json";

	$resource = json_decode(TDT::HttpRequest($url)->data);

	include_once ("templates/TheDataTank/header.php");

	echo "<h1>" . $module . "/" . $resourcename . "</h1>";
	//get a sequence of the parameters
	$args = "";
	
	if(sizeof(($resource->requiredparameters)) > 0) {
	    $params = $resource->requiredparameters;
	    foreach($params as $var) {
		$args .= "%$var%/";
	    }
	}
	// build the proper URL's to invoke when doing a call for a certain resource
	$url = Config::$HOSTNAME . CONFIG::$SUBDIR."$module/$resourcename/$args";
	echo "<a href=\"$url\">$url</a>";
	echo "<h3>Description</h3>";
	echo "<p>" . $resource->doc . "</p>";
	if(sizeof($resource->parameters) > 0) {
	    echo "<h3>All possible parameters:</h3>";
	    echo "<ul>\n";
	    foreach($resource->parameters as $var => $doc) {
		echo "<li><strong>$var:</strong> $doc\n";
	    }
	    echo "</ul>\n";
	} else {
	    echo "<h3>This resource has no parameters.</h3>";
	}

	echo "<h4>You can use RESTful identifiers on any resource</h4>";

	echo "<p><a href=\"/".Config::$SUBDIR."docs/\">&laquo; Back to the datasets</a></p>";
	include_once ("templates/TheDataTank/footer.php");
    }

}
?>
