<?php
/* Copyright (C) 2011 by iRail vzw/asbl
 *
 * Author: Pieter Colpaert <pieter aŧ iRail.be>
 * License: AGPLv3
 *
 * This file prettyprints autogenerated API Documentation
 */
ini_set("include_path", "../");

//get the right variables or redirect to home
if(!isset($_GET["module"]) || !isset($_GET["method"])){
     header("Location: /");
     exit(0);
}

$module = $_GET["module"];
$method = $_GET["method"];

//include the right class
include_once("modules/" . $module . "/" . $method .".class.php");
include_once("templates/TheDataTank/header.php");

echo "<h1>" . $module."/". $method ."</h1>";
//get a sequence of the parameters
$args = "";
if(sizeof($method::getRequiredParameters()) > 0){
     $params = $method::getRequiredParameters();
     $args="?" . $params[0] . "=...";
     $i = 0;
     foreach($params as $var){
	  if($i == 0) continue;
	  $args .= "&$var=...";
	  $i++;
     }
}
echo "<strong>" . $method::getDoc() ."</strong>";
$url = "http://".$_SERVER["SERVER_NAME"] . "/$module/$method/$args";
echo "<h4><a href=\"$url\">$url</a></h4>";
echo "<ul>\n";
echo "<h4>All possible parameters</h4>";
foreach($method::getParameters() as $var => $doc){
     echo "<li><strong>$var:</strong> $doc\n";
}
echo "</ul>\n";
echo "<br/>";
include_once("templates/TheDataTank/footer.php");

?>