<?php
/* Copyright (C) 2011 by iRail vzw/asbl
 *
 * Author: Pieter Colpaert <pieter aŧ iRail.be>
 * License: AGPLv3
 *
 * This file prettyprints autogenerated API Documentation
 */
ini_set("include_path", "../");
include_once("error/Exceptions.class.php");

/**
 * Get all derived classes from another class
 */
function getAllDerivedClasses($classname){
     $result = array();
     foreach(get_declared_classes() as $class){
	  if(get_parent_class($class) == $classname){
	       $result[] = $class;
	  }
     }
     return $result;
}

//print page
include_once("templates/TheDataTank/header.php");

echo "<h1>Modules and methods</h1>";
if ($handle = opendir('../modules/')) {
     $done_methods = array();
     while (false !== ($modu = readdir($handle))) {
	  if ($modu != "." && $modu != ".." && is_dir("../modules/" . $modu)) {
	       echo "<h3>$modu</h3>\n";
	       if ($handle2 = opendir('../modules/' . $modu)) {
		    while (false !== ($metho = readdir($handle2))) {
			 //Check if it is a rightfull php class
			 $arr = explode(".class.", $metho);
			 if ($metho != "." && $metho != ".." && sizeof($arr) > 1) {
			      include_once("modules/" . $modu . "/" . $metho);
			 }
		    }
		    closedir($handle2);
	       }
	       echo "<lu>";
	       foreach(getAllDerivedClasses("AMethod") as $class){
		    //BUG; functions with same name don't get shown!!!
		    if(!in_array($class,$done_methods)){
			 echo "<li><a href=\"/docs/$modu/$class/\">$class</a> - ". $class::getDoc() ."</li>";
			 $done_methods[] = $class;
		    }
	       }
	       echo "</lu>";
	  }
     }
     closedir($handle);
}

echo "<h1>Errors</h1>";

foreach(getAllDerivedClasses("AbstractTDTException") as $class){
     echo "<h4>".$class::$error." - $class</h4>";
     echo $class::getDoc();
     echo "<br/>";
}

include_once("templates/TheDataTank/footer.php");
?>