<?php

/**
 * Executes the ColumnSelectionFilter filter
 * 
 * @package The-Datatank/universalfilter/interpreter/executers
 * @copyright (C) 2012 by iRail vzw/asbl
 * @license AGPLv3
 * @author Jeroen Penninck
 */
class ColumnSelectionFilterExecuter extends UniversalFilterNodeExecuter {
    
    public function evaluateAsExpressionHeader(UniversalFilterNode $filter, Environment $topenv, IInterpreter $interpreter){
        throw new Exception("A ColumnSelectionFilter can not be evaluated.");
    }
    
    public function evaluateAsExpression(UniversalFilterNode $filter, Environment $topenv, IInterpreter $interpreter) {
        throw new Exception("A ColumnSelectionFilter can not be evaluated.");
    }
    
    public function execute(UniversalFilterNode $filter, IInterpreter $interpreter) {
        //get source environment
        $executer = $interpreter->findExecuterFor($filter->getSource());
        $environment = $executer->execute($filter->getSource(), $interpreter);
        
        //the table generated by the last executer
        $sourcetable = $environment->getLastTable();
        
        // create a new environment to give each column (once for each row)
        $newEnv=$environment->newModifiableEnvironment();
        
        //get the columns to filter
        $columnInterpreters = $filter->getColumnData();
        
        //do it for each row, so create a new header which tells that
        $singleRowHeader = $sourcetable->getHeader()->cloneHeader();
        $singleRowHeader->setIsSingleRowByConstruction(true);
        
        
        //create a new empty table of the same size.
        $newRows = array();
        foreach($sourcetable->getContent()->getRows() as $row){
            array_push($newRows, new UniversalFilterTableContentRow());
        }
        
        // the header for the returned table:
        $columnNames = array();
        $tableLinks = array();
        
        
        //loop all columns
        foreach($columnInterpreters as $column){
            //this column
            $filterColumn =$column->getColumn();
            //find something to evaluate it
            $exprexec = $interpreter->findExecuterFor($filterColumn);
            
            //the name for the column
            $columnName = $column->getAlias();
            
            // ============> TODO: getDefaultColumnName...
            
            
            //request the header
            $singleRowTable = new UniversalFilterTable($singleRowHeader, new UniversalFilterTableContent(array(new UniversalFilterTableContentRow())));
            $newEnv->replaceCurrentTable($singleRowTable);
            
            $header = $exprexec->evaluateAsExpressionHeader($filterColumn, $newEnv, $interpreter);
            
            //check header
            if(!$header->isSingleRowByConstruction()){
                throw new Exception("Not a valid column-expression in column selection filter!");
            }
            
            //add the name of the new column
            array_push($columnNames, $columnName);
            
            //add link info
            if($header->isLinkedColumn($header->getColumnName())){
                array_push($tableLinks, array(
                    "table" => $header->getLinkedTable($header->getColumnName()),
                    "key" => $header->getLinkedTableKey($header->getColumnName())
                    ));
            }
            
            foreach($sourcetable->getContent()->getRows() as $index => $row){
                // make a table with only this row
                $singleRowTable = new UniversalFilterTable($singleRowHeader, new UniversalFilterTableContent(array($row)));
                $newEnv->replaceCurrentTable($singleRowTable);

                //request the content
                $anwser = $exprexec->evaluateAsExpression($filterColumn, $newEnv, $interpreter);
                
                //set the value in the row
                $newRows[$index]->defineValue($columnName, $anwser->getCellValue($header->getColumnName()));
            }
        }
        
        
        //the new header
        $newTableHeader=new UniversalFilterTableHeader($columnNames, $tableLinks, false, false);
        
        //the new table
        $newtable = new UniversalFilterTable($newTableHeader, new UniversalFilterTableContent($newRows));
        
        //add it to the environment
        $environment->addTable($newtable);
        
        return $environment;
    }
}

?>
